### ISSUE TITLE
[FEATURE] Blog Views Functionallity

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#336]
### Detailed description

Blog Views Functionallity
when user visits any blogs, then blog count should increate by 1

![image](https://user-images.githubusercontent.com/44284877/209844110-9a1523dd-8829-4442-8bd0-cd7373bf0519.png)

backend: [https://github.com/thecyberworld/api.thecyberhub.org](https://github.com/thecyberworld/api.thecyberhub.org)  

code is on the dev branch:
- fork this repo
- clone this repo
- add your mongo creds in the env file
- npm run server

frontend: [https://github.com/thecyberworld/thecyberhub.org](https://github.com/thecyberworld/thecyberhub.org)
- npm run dev

### Context

If you need any help or having doubts, let us know

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nidhiparab** [comment]
Hey I am having trouble connecting the backend. I have added the mongo_uri
![image](https://user-images.githubusercontent.com/89039068/210324077-dc70f673-1cb2-4321-9474-7c7d0fe4aeeb.png)
I have reached till here but I have no idea how to proceed further inorder to design.

Can anyone help me with the setup?

**Comment by kabir0x23** [comment]
hello @nidhiparab

**Comment by kabir0x23** [comment]
wait a minutue

**Comment by kabir0x23** [comment]
go to connect 
then you will get multiple options 
first you can connect that with mongodb compass (you have to download the compass app then have to paste that url in it)

**Comment by kabir0x23** [comment]
and for connecting with the application 
you have to click on the Connect with the application 
then you will get a url

add your details and database name over there
then add it into backend env file

**Comment by kabir0x23** [comment]
If you face any issues let us know

**Comment by nidhiparab** [comment]
> and for connecting with the application you have to click on the Connect with the application then you will get a url
> 
> add your details and database name over there then add it into backend env file

I have already done this step. I am not able to see the create blog or profile section, a little help with that please?

**Comment by kabir0x23** [comment]
> > and for connecting with the application you have to click on the Connect with the application then you will get a url
> > add your details and database name over there then add it into backend env file
> 
> I have already done this step. I am not able to see the create blog or profile section, a little help with that please?

Nice

profile section is in the 
![image](https://user-images.githubusercontent.com/44284877/210347444-fe55ace6-8a41-47ca-9278-d8c1a796caec.png)

you can create blogs via clicking on create blog button:
![image](https://user-images.githubusercontent.com/44284877/210347556-3fbc7718-433c-4d49-815f-a2c83377e77a.png)

**Comment by kabir0x23** [comment]
i am just uploading the latest structure of the blogs 
![image](https://user-images.githubusercontent.com/44284877/210347646-b1e552d1-e695-40f6-a330-1f9851b7aa75.png)

so make sure to keep fetching the new changes before working on the code..
![image](https://user-images.githubusercontent.com/44284877/210347694-37438c27-ad26-4ce4-83e0-91c3cfd75559.png)

**Comment by nidhiparab** [comment]
![image](https://user-images.githubusercontent.com/89039068/210348903-35caa8d8-140b-44ca-aad5-e1b45ddc64ff.png)
Sorry but I don't see the profile option anywhere

**Comment by nidhiparab** [comment]
Even the navbar in Readme is different than what I cloned. Could you look into that?

**Comment by kabir0x23** [comment]
okay got it

**Comment by kabir0x23** [comment]
You have to clone the dev branch
when you fork the repo, there is option 
- [ ] copy only main branch

uncheck that button while forking

**Comment by kabir0x23** [comment]
if you are using github desktop, then maybe you can change the branch from the eaily

**Comment by kabir0x23** [comment]
backend branch: dev
frontend branch: dev

**Comment by kabir0x23** [comment]
and make sure to 
![image](https://user-images.githubusercontent.com/44284877/210369597-0b942841-3125-4c8a-969a-33dd66823197.png)

uncomment the localhost one in vite.js config file in frontned
if you don't, you will get the backed of the main website, not the local

**Comment by kabir0x23** [comment]
and env file too
![image](https://user-images.githubusercontent.com/44284877/210369902-8b3c4772-1c3a-4171-b8e8-09f01e1e9ab5.png)

**Comment by kabir0x23** [comment]
hey @nidhiparab 

Just fetch the new changes from dev branch
you don;t have to make any changes to env or config file after that
...
