### ISSUE TITLE
[FEATURE] Improve the Profile Update poge layout and design

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#346]
### Detailed description

Improve the layout and design of the blogs page
local: http://localhost:3000/profile > edit profile

![image](https://user-images.githubusercontent.com/44284877/210176660-e4bae4c9-9033-4c9d-b3bc-da6f4ef8db91.png)

### Context

Code is on dev branch
you have to setup the backend and frontend
add your MongoDB url into the env on backend

frontend: https://github.com/thecyberworld/thecyberhub.org

backend: https://github.com/thecyberworld/api.thecyberhub.org

### Additional information

Hello and welcome to our issue tracker!

We're here to help with any issues or questions you may have about the project. 

If you need more immediate assistance, you can also reach us on our support channel at [Discord](https://discord.gg/QHBPq6xP5p). We're here to help, so don't hesitate to reach out.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rahul-Palamarthi** [comment]
can you assign this issue, i can work on this 🚀

**Comment by kabir0x23** [comment]
> can you assign this issue, i can work on this 🚀

Hey, this is an old page, 

you have to find a new code for this page

**Comment by Rahul-Palamarthi** [comment]
> > can you assign this issue, i can work on this 🚀
> 
> Hey, this is an old page,
> 
> you have to find a new code for this page

@kabir0x23 
Right now there is nothing even after login in the production app
![image](https://github.com/thecyberworld/TheCyberHUB/assets/87606332/84d48406-074b-4ab3-94c7-d22233eba5cd)
should I add the code ?

**Comment by kabir0x23** [comment]
> > > can you assign this issue, i can work on this 🚀
> > 
> > 
> > Hey, this is an old page,
> > you have to find a new code for this page
> 
> @kabir0x23 Right now there is nothing even after login in the production app

checkout this is issue first 

https://github.com/thecyberworld/TheCyberHUB/issues/448
