### ISSUE TITLE
[FEATURE] Improve the Dashbaord Layout

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#441]
### Detailed description

We have to improve the dashboard layout

![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/c7d44861-086a-4e58-919a-ecd7fc928ede)

### Context

- We have to make the dashboard user-friendly

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Arun-cn** [comment]
can i work on this issue

**Comment by kabir0x23** [comment]
> can i work on this issue ? Please assign it to me

That's Great

We have assigned this to you..

Thank you.

**Comment by kabir0x23** [comment]
@Arun-cn  hey are you working on this issue?

if yes, checkout dev branch and checkout settings page, u can make this one similar to that
