### ISSUE TITLE
[FEATURE] NoteTaking App In Dashboard

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#442]
### Detailed description

NoteTaking App Summary
Features:
- Note Creation: Users can easily create and organize notes for various purposes.
- Markdown Editing: The app supports rich text formatting, allowing users to emphasize important information using bold, italics, bullet points, and more.

### Context

Building a basic NoteTaking Application for the community is an important and impactful project. Here's a brief summary of its significance:

- Easy Note-Taking: The app will provide a user-friendly interface for taking and managing notes, making it simple for anyone to jot down and organize their thoughts, ideas, and information.

 - Accessible Anytime: Users will have 24/7 access to their notes, ensuring they can retrieve and edit their information whenever and wherever they need it.

By developing this basic NoteTaking Application, we empower the community to become more organized and efficient in managing their notes, fostering better information retention and accessibility for all.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kabewh** [comment]
picking this up

**Comment by kabir0x23** [comment]
That's Great

We have assigned this to you..

Thank you.
