### ISSUE TITLE
Message icon is in middle in mobile version

### ISSUE THREAD

**Issue by Rahul-Palamarthi** [thecyberworld/TheCyberHUB#443]
### What would you like to share?

![Screenshot_20231001-174307](https://github.com/thecyberworld/TheCyberHUB/assets/87606332/5a0ba09d-9806-4dff-9314-4e519989fb3d)
I would like to fix it, can you assign it to me

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
That's Great

We have assigned this to you..

Thank you.

**Comment by Rahul-Palamarthi** [comment]
🙂

**Comment by Rahul-Palamarthi** [comment]
@kabir0x23 I have fixed the issue 🚀
