### ISSUE TITLE
[BUG] Footer Social Icons Overflow Issue on Mobile View

### ISSUE THREAD

**Issue by Arun-cn** [thecyberworld/TheCyberHUB#445]
### Describe the bug

In the mobile view of our website, we have encountered a bug where the social icons in the footer section are overflowing, causing a display issue. the footer box to small to inculde all icons

### To Reproduce

Scroll down to bottom to see the bug

### Expected Behavior

all the icons in the box must be present

### Screenshot/ Video

![IMG_20231001_184152](https://github.com/thecyberworld/TheCyberHUB/assets/53257113/9b816e36-702a-4e73-9639-40dc9ef1da43)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Surajit0573** [comment]
Hi @kabir0x23, I can fix this problem. Can you please assign me to this issue !!

**Comment by kabir0x23** [comment]
> Hi @kabir0x23, I can fix this problem. Can you please assign me to this issue !!

hey, this issue has already been assigned to another person, u can checkout other issue or can create new well.

**Comment by Surajit0573** [comment]
Ok, Thanks for your response
