### ISSUE TITLE
[FEATURE] Settings Edit Main Profile Page

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#448]
### Detailed description

We want to have a settings page for a user
- to edit username, password and email only

where u can add these options 
> options dropdown > settings
> options dropdown > dashboard > settings

![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/3396f43f-5b19-4a8e-a262-1e3a911391d6)

### Context

- with this user can edit their profile

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rahul-Palamarthi** [comment]
Can I know the url of the edit profile page?

**Comment by kabir0x23** [comment]
> Can I know the url of the edit profile page?

 can create one in the app.jsx or dashboardroutes.jsx
 
 userprofile or profile both are different
 
 here is the main code, for this issue: src/components/Dashboard/Profile/EditProfile.jsx
 
 you can make a settings page in the dashboard/settings/profile
 
 something like this
 
 if u will have anyy issues or doubts, feel freee to oing

**Comment by Rahul-Palamarthi** [comment]
> > Can I know the url of the edit profile page?
> 
> can create one in the app.jsx or dashboardroutes.jsx
> 
> userprofile or profile both are different
> 
> here is the main code, for this issue: src/components/Dashboard/Profile/EditProfile.jsx
> 
> you can make a settings page in the dashboard/settings/profile
> 
> something like this

![image](https://github.com/thecyberworld/TheCyberHUB/assets/87606332/52a0a84b-1064-4c3f-bbcf-20c0d88715ec)


i will be adding an option _**Setting**_ in the side-menu and when the user clicks on the _**Settings**_ they will be navigated to the <code>dashboard/settings/profile</code> and the settings page will be same as above

**Comment by Rahul-Palamarthi** [comment]
can we use shadcn UI for this? because it will be easier

**Comment by SharmaKunal14** [comment]
Hi @kabir0x23, I can work on this issue. please assign

**Comment by kabir0x23** [comment]
> can we use shadcn UI for this? because it will be easier

Okay go for it, and can u get the similar design with left nav as well in

note we have to use jsx only, no tsx here

**Comment by kabir0x23** [comment]
> Hi @kabir0x23, I can work on this issue. please assign

Hey, as this issue has already been assigned to another one

u can work on other issue or can create new by self

**Comment by Rahul-Palamarthi** [comment]
> > Hi @kabir0x23, I can work on this issue. please assign
> 
> Hey, as this issue has already been assigned to another one
> 
> u can work on other issue or can create new by self

Sure

**Comment by kabir0x23** [comment]
> > > Hi @kabir0x23, I can work on this issue. please assign
> > 
> > 
> > Hey, as this issue has already been assigned to another one
> > u can work on other issue or can create new by self
> 
> Sure

@Rahul-Palamarthi are u going to work on this one?

**Comment by Rahul-Palamarthi** [comment]
> > > > Hi @kabir0x23, I can work on this issue. please assign
> > > 
> > > 
> > > Hey, as this issue has already been assigned to another one
> > > u can work on other issue or can create new by self
> > 
> > Sure
> 
> @Rahul-Palamarthi are u going to work on this one?

Yes, I will work on this issue

**Comment by Rahul-Palamarthi** [comment]
> ### Detailed description
> We want to have a settings page for a user
> 
> * to edit username, password and email only
> 
> where u can add these options
> 
> > options dropdown > settings
> > options dropdown > dashboard > settings
> 
> ![image](https://user-images.githubusercontent.com/44284877/271833387-3396f43f-5b19-4a8e-a262-1e3a911391d6.png)
> 
> ### Context
> * with this user can edit their profile
> 
> ### Possible implementation
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

@kabir0x23 should i also make the sidebar in the image above ??

**Comment by kabir0x23** [comment]
> > ### Detailed description
> > We want to have a settings page for a user
> > 
> > * to edit username, password and email only
> > 
> > where u can add these options
> > 
> > > options dropdown > settings
> > > options dropdown > dashboard > settings
> > 
> > ![image](https://user-images.githubusercontent.com/44284877/271833387-3396f43f-5b19-4a8e-a262-1e3a911391d6.png)
> > 
> > ### Context
> > * with this user can edit their profile
> > 
> > ### Possible implementation
> > _No response_
> > 
> > ### Additional information
> > _No response_
> > 
> > ### Code of Conduct
> > * [x]  I agree to follow this project's Code of Conduct
> 
> @kabir0x23 should i also make the sidebar in the image above ??

Yes

**Comment by Rahul-Palamarthi** [comment]
@kabir0x23 

here are the updates just few minor changes are remaining

![image](https://github.com/thecyberworld/TheCyberHUB/assets/87606332/49fb31bb-badd-4bac-9f49-4f891e0a0315)

**Comment by kabir0x23** [comment]
> @kabir0x23
> 
> here are the updates just few minor changes are remaining
> 
> ![image](https://user-images.githubusercontent.com/87606332/271906792-49fb31bb-badd-4bac-9f49-4f891e0a0315.png)

looks amazing 👍
