### ISSUE TITLE
[FEATURE] Add Contributor List to Readme

### ISSUE THREAD

**Issue by ayushmankoley** [thecyberworld/TheCyberHUB#450]
### Detailed description

Adding Contributor list to Readme file

### Context

Gives contributors recognition

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
Hey, thanks for raising an issue

About contributors, those are already getting reflected on the right side of the window, that's why we also have not implemented that one..

You can raise other issue as well

Thank you
