### ISSUE TITLE
[BUG] In mobile view the footer social media icons are overflowing from the box

### ISSUE THREAD

**Issue by hustlerZzZ** [thecyberworld/TheCyberHUB#452]
### Describe the bug

The padding of the box is way too less.
I want to fix this issue kindly assign this to me.

### To Reproduce

Increase the padding a little bit.

### Expected Behavior

Normal view as like any other footer.

### Screenshot/ Video

![Screenshot_20231002-065355](https://github.com/thecyberworld/TheCyberHUB/assets/102817420/b16f9dc5-2a50-4e80-9278-e1592077c20d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
https://github.com/thecyberworld/TheCyberHUB/issues/445

**Comment by hustlerZzZ** [comment]
My mistake
