### ISSUE TITLE
[BUG] In mobile view the community links cards are not looking good

### ISSUE THREAD

**Issue by hustlerZzZ** [thecyberworld/TheCyberHUB#453]
### Describe the bug

[🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

In each card the text and icon should be in a row but they are in a column. I think we should fix them as soon as we can.
Kindly assign this issue to me so that I can fix this.

### To Reproduce

Set the display to flex

### Expected Behavior

The text and icon should be in a row

### Screenshot/ Video

![Screenshot_20231002-070056](https://github.com/thecyberworld/TheCyberHUB/assets/102817420/03151639-5fc8-4238-9fa5-fa097944bbb5)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
@hustlerZzZ hey are you working on this issue?

**Comment by hustlerZzZ** [comment]
> @hustlerZzZ hey are you working on this issue?

It's causing some errors I am fixing them. It's showing white screen only. I will try to fix it otherwise I will let you know.
Thanks and regards

**Comment by kabir0x23** [comment]
> > @hustlerZzZ hey are you working on this issue?
> 
> It's causing some errors I am fixing them. It's showing white screen only. I will try to fix it otherwise I will let you know. Thanks and regards

try different browser

**Comment by kabir0x23** [comment]
Hey @hustlerZzZ, are u working on this issue

**Comment by hustlerZzZ** [comment]
> Hey @hustlerZzZ, are u working on this issue

Sorry, something is wrong I am not able to work on this. Feel free to assign someone else

**Comment by itsankitbhusal** [comment]
can I work on this issue? @kabir0x23

**Comment by itsankitbhusal** [comment]
Worked on the issue and is fixed, have a look once at my pull request #497 
@kabir0x23

**Comment by kabir0x23** [comment]
> Worked on the issue and is fixed, have a look once at my pull request #497 @kabir0x23

Yeah will merge it soom , just thinking about the design for mobile view
