### ISSUE TITLE
[BUG] : Twitter logo is not updated

### ISSUE THREAD

**Issue by Rohit-Sharmaa** [thecyberworld/TheCyberHUB#455]
### Describe the bug

the logo of the twitter is not updated 

### To Reproduce

Go to '.Website..'
Scroll down 
See the logo of the twitter

### Expected Behavior

The logo of the twitter should be changed to new logo of twitter

### Screenshot/ Video

<img width="847" alt="Screenshot 2023-10-02 144823" src="https://github.com/thecyberworld/TheCyberHUB/assets/130988755/c0a947af-82f0-46c7-bc03-742fca08131b">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
Nice

 you can also rename it to X

**Comment by Rohit-Sharmaa** [comment]
@kabir0x23 Yah sure and soon i will make a pr

**Comment by Durgeshsejekar** [comment]
I want to work on this issue so please can u assign me.

**Comment by Rohit-Sharmaa** [comment]
@Durgeshsejekar  I am working on this issue already . Please , You can work on some other issue.

**Comment by kabir0x23** [comment]
> @kabir0x23 not able to start the server because there is no app.js file in the code .
> I just want to know which file i need to run with node so the our localhost:3000 server should be running

npm run dev

For starting points in project, u can find those in package.json file.
