### ISSUE TITLE
[FEATURE] Add Loading Spinner For Components In "Explore" Route

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#459]
### Detailed description

- [x] When we click the "Explore" Route in the navigation bar, first we don't see any users but after few seconds it appears from nowhere. We should add loading spinner while the data of users is loading.
- [x] When we click on the options in the right menu for example "Users", "Blogs", "CFT", "Feeds", we don't see spinner.

- [x] When there are no data appears from those component we should see "There are no Blogs" ("There are no `<The Component data>`").
(This may be better to add in different issue, tell me your thought)

* I would like to handle it under hacktoberfest event , please assign me.

### Context

- It is better user experience that the user will know that something should appear in this place, so the user will wait for it. 
- Also, when there is no data the user will know that the page is not blank without a reason.

### Possible implementation

- [x] Manage Loading State in "Users", "Blogs", "CFT", "Feeds" Components and using the LoadingSpinner component.
- [x] In the right places check if the data object is empty and render on screen relevant message.

### Additional information

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/3b4d1e00-8758-4f1a-b96f-54ff6f213c57

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@kabir0x23

**Comment by kabir0x23** [comment]
> @kabir0x23

nice, i have assigned this issue to you
