### ISSUE TITLE
[BUG] Mobile Display - When Menu Is Open Scrollable Background, {branch: dev}.

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#462]
### Describe the bug

On mobile display, when the user opens the menu, the background is scrollable. I am not sure if calling it a bug but the background needs to stay in place.

* I would like to handle it under hacktoberfest event , please assign me.

### To Reproduce

1. Open in mobile display
2. Scroll down the background 

### Expected Behavior

When the user opens the menu, only the menu needs to be scrollable in case , there are more menu tabs.
The background doesn't need to be scrollable

### Screenshot/ Video

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/b177e8ad-0eac-4c5a-be28-2ff8d3b8051c

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@kabir0x23

**Comment by ArkadiK94** [comment]
What do you think about it? Is it necessary to change as I said? Or leave it as it is.

**Comment by kabir0x23** [comment]
> What do you think about it? Is it necessary to change as I said? Or leave it as it is.

hey,

u are viewing this on website, so when u use mobile u won't face any issue like this,

 as of now, how it is effecting on website, and how it can be fixed?

**Comment by ArkadiK94** [comment]
https://github.com/thecyberworld/TheCyberHUB/assets/76536506/c9947ac3-9c43-40b7-b6f3-a8461b444176

It is happens in the mobile. Before, I recorded the website when it is in display width of mobile. We should fix it because It feels strange and bad user experience. 
I don't have an answer yet about how to fix it. If it needed,  I will try to figure it out.

**Comment by kabir0x23** [comment]
> Screen_Recording_20231007_220938_Chrome.mp4
> 
> It happens in the mobile. Before, I recorded the website when it is in display width of hamburger menu which happens in the mobile as well. We should fix it because It feels strange and bad user experience. I don't have an answer yet about how to fix it. If it is needed, I will try to figure it out.

Okayy, nice
