### ISSUE TITLE
[FEATURE] CTF Design Improvement, {branch: dev}.

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#466]
### Detailed description

[🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

url: https://www.thecyberhub.org/ctf
![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/d0b5e342-777e-4df2-8e5f-c7dd65e94609)

### Context

We have to improve the design of the CTF section

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsankitbhusal** [comment]
@kabir0x23 what exactly do I need to improve in the CTF? can you elaborate more about he feature?

**Comment by kabir0x23** [comment]
> @kabir0x23 what exactly do I need to improve in the CTF? can you elaborate more about he feature?

any new  design, just have to improve

fix: when we submit, all of the submit buttons gets triggered, same for when ans is correct, solved is getting reflected in all of the buttons

**Comment by ArkadiK94** [comment]
>fix: when we submit, all of the submit buttons gets triggered, same for when ans is correct, solved is getting reflected in all of the buttons

I would like to try fixing it. In addition when we click the refresh button the "submit" button refreshes as well. Strange behavior.
Please, assign me.

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/0cbb086e-dd1a-4f9b-a762-8b454f1cf687

**Comment by kabir0x23** [comment]
@ArkadiK94 

here when we submit, 
in all of the submit, it start showing loading process, we can also fix that

**Comment by ArkadiK94** [comment]
@kabir0x23 I will work on different issue for now, could you reassign me from here.
