### ISSUE TITLE
[FEATURE] Improve the Leaderboard Design [FEATURE] CTF Design Improvement, {branch: dev}.

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#467]
### Detailed description

note: **branch: dev**, while forking, make sure to uncheck <u>*copy only main branch* </u> to get the dev branch in your fork
url: https://www.thecyberhub.org/leaderboard
![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/b5f768ef-c54e-40b8-afb6-1a44dbe60cd1)

[](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/a73b241c-74e9-4f80-946d-bd1363a3f75c)

### Context

Improvement In Leaderboard section

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsankitbhusal** [comment]
@kabir0x23 can you please assign me this issue, I want to contribute.

**Comment by kabir0x23** [comment]
> @kabir0x23 can you please assign me this issue, I want to contribute.

Hey, any desgin in your mind?

**Comment by itsankitbhusal** [comment]
first of all, I am thinking of arranging the user names in left aligned, in a way that it will still be aligned in the center and will improve other things in the way

**Comment by kabir0x23** [comment]
> first of all, I am thinking of arranging the user names in left aligned, in a way that it will still be aligned in the center and will improve other things in the way

okkay, uu also can improve the design and colors if needed

thank yyou

**Comment by itsankitbhusal** [comment]
@kabir0x23 changes are made and pushed to the repo as a pull request #470.
