### ISSUE TITLE
[FEATURE] Timeline/Events page, {branch: dev}.

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#471]
### Detailed description

We have to implement this events page under Opportunities>Events 

Desgin layout:
![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/6d1582d5-9f47-4626-98e6-59109feec1f5)

### Context

This will help users to see upcoming events in better design

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TandinDev** [comment]
Is this issue contain only the design or we can an interactive between Frontend and DB?

**Comment by kabir0x23** [comment]
> Is this issue contain only the design or we can an interactive between Frontend and DB?

As of now it's only frontend, like if you want to work on db, then you can that too.

if u want to work with frontend only as of now, u can setup dummy data in .json file

**Comment by TandinDev** [comment]
I can work on this. :)

**Comment by TandinDev** [comment]
Updating the status here, reach till here. Adding animation and some effects:

![Screenshot from 2023-10-09 19-20-15](https://github.com/thecyberworld/TheCyberHUB/assets/62091702/60984a5d-1510-4573-bcdf-64fc3be9a643)

**Comment by TandinDev** [comment]
@kabir0x23 I am done with this, can you please review this PR: https://github.com/thecyberworld/TheCyberHUB/pull/499

**Comment by TandinDev** [comment]
Hey @kabir0x23 I belive it won't get counted in hacktoberfest if this issue isn't close. Can you do that for me or is there anything I need to add on it?
