### ISSUE TITLE
[FEATURE] Improve Dashboard Layout and desgin, {branch: dev}

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#472]
### Detailed description

- Toggle to short the sidebar (hide sidebar text)
- No need of searchbar
- Design layout:
![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/5acfc33a-61f7-4f07-92bd-0bfcaff0340c)

### Context

Improve design will help in better user experience 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TandinDev** [comment]
Can i work on this issue?

**Comment by kabir0x23** [comment]
> Can I work on this issue?

Hey

If you have any questions or doubts, feel free to ask here

thank you.

**Comment by TandinDev** [comment]
Hey @kabir0x23 I fork this repo and made a new branch from dev. I explored the website, but I coudn't find the above page?
can you help me on it?

**Comment by TandinDev** [comment]
Hey @kabir0x23 I understood the assignment. Thank you.

**Comment by TandinDev** [comment]
@kabir0x23 This issue is done, can you please review this PR: https://github.com/thecyberworld/TheCyberHUB/pull/481
