### ISSUE TITLE
[FEATURE] Improve Notes App, {branch: dev}.

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#474]
### Detailed description

[🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

- Dashboard > Notes
- Design Layout: as of now simple design requirement
![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/0260cdb3-9907-48ed-8bf4-3667c2e5303b)

### Context

This will help community members to store their notes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SuyashRajput** [comment]
Can you elaborate this issue
like where do you want this notes app improvement

**Comment by SuyashRajput** [comment]
If you want a notes section on the main navbar
I can make a local storage notes storing page
Something like this( don't worry I will change the colour scheme )
![image](https://github.com/thecyberworld/TheCyberHUB/assets/110171204/ac8b3b87-3c0e-495e-81b8-bee0d9f5b48c)

**Comment by kabir0x23** [comment]
> Can you elaborate on this issue like where you want this notes app improvement

we just have to create this simple note app (only frontend as of now)

![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/dca10412-923a-4b38-9a08-ad1ab5355c45)

left side title | right side description

**Comment by kabir0x23** [comment]
@ArkadiK94

**Comment by ArkadiK94** [comment]
First pr was pushed,
Still left to do in next pr's
- [ ] add option to pin note 
- [ ] add option to create/edit/delete note
- [ ] add items in the menu icon 
- [ ] add markdown editor setup
- [ ] add mobile layout
- [ ] clean previous code which I commented for now , and put it in "old" folder

**Comment by ArkadiK94** [comment]
- [ ] when delete note/ edit note and remove img / don't save note --> remove the img from s3

**Comment by ArkadiK94** [comment]
some tasks that we need to fix:
- [ ] In the md editor the bold/italic (and more) buttons do not work properly when we toggle them without an order.
- [ ] when we click on one of these buttons, it does not save the clicked state and does not displayed properly.

**Comment by ArkadiK94** [comment]
Need to add related to Categories :
- [ ] need to add functionality for adding/removing/editing category:

1. add by icon , when clicking the icon will be opened a modal window to create category
2. remove category and edit category mode will be chosen from menu, when choose this mode the icon will be changed to the right one and user could pick a category and click the icon to remove or edit

- [ ] change category of note , when the user will drag the note to different category and drop there the note's category will be changed accordingly
- [ ] redux for categories and backend...

**Comment by ArkadiK94** [comment]
- [ ] change the notes category prop when edit the name of the current category so the notes will still be in this folder
- [ ] change the notes category prop when remove a category so if the user will create again this category the notes will not be

**Comment by ArkadiK94** [comment]
- [ ] add in the note description in edit/add note mode an option to pick/change the category
- [ ] related to back-end, If the user added many categories (like 4 categories) at one time there is an 429 error "to many requests" so change it / make the number bigger.
- [ ] there is a grey box in upper side and lower side of the scroll bar. remove it.

**Comment by ArkadiK94** [comment]
Issues #559, #560, #561, #562, #563  , I split what left to do in many issues. we can close this issue.
