### ISSUE TITLE
[BUG] fix fead post design in explore section, {branch: dev}.

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#476]
### Describe the bug

[🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

url: https://dev.thecyberhub.org/#/explore
![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/d7dfcd3e-7fa1-47c4-b5e3-350b67509d2a)

as we can see the height of the other feeds depending on the max height feed
fix: it is fine in row. but looking bad in column, exmaple 3rd feed height should be it's own, instead of above feed heights 

### To Reproduce

go to: https://dev.thecyberhub.org/#/explore

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mayank2002-jpg** [comment]
Hi @kabir0x23 kindly assign me this issue. I Love to work on this issue

**Comment by mayank2002-jpg** [comment]
Thanks for assigning me this issue

**Comment by kabir0x23** [comment]
Hey @mayank2002-jpg are u working on this issue

**Comment by 0xlarmideh** [comment]
@kabir0x23 Can I work on this?

**Comment by kabir0x23** [comment]
> @kabir0x23 Can I work on this?

Okay i have assigned this issue to you..

and make sure to follow this [🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

Thank you.

**Comment by ArkadiK94** [comment]
@kabir0x23 is it still in progress?

**Comment by kabir0x23** [comment]
yes

![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/985892bb-b970-42f7-9e43-2c447068c970)

**Comment by ArkadiK94** [comment]
@0xlarmideh Do you still work on it?

**Comment by 0xlarmideh** [comment]
No

**Comment by iiDaVoDkA** [comment]
i would love to work on this please
