### ISSUE TITLE
[FEATURE] Poll option in Feeds, {branch: dev}.

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#477]
### Detailed description

[🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

Feeds: https://dev.thecyberhub.org/#/feeds
![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/ca419426-3bd1-449c-a97e-6b631e0bc0f3)

Feature:
- 
![13f4728542cfb30c0724f46fb59e1368](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/95f296e3-628d-475d-9e1f-46c72bcc7ce4)

### Context

This will help users to create a poll.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Saedbhati** [comment]
can you assign these to me?

**Comment by kabir0x23** [comment]
Sure

If u will have any question, feel free to ask below

Thank you,

**Comment by kabir0x23** [comment]
Hey @Saedbhati , are u working on this issue?

**Comment by taran1326** [comment]
Hey @kabir0x23 do we have to implement exact same ui for poll feature ?

**Comment by kabir0x23** [comment]
> Hey @kabir0x23 do we have to implement exact same ui for poll feature ?

Hey

yes we can build similar

first one is before 
second one is when we submit our ans it show's that

**Comment by taran1326** [comment]
hey do you have some relevant resources to start with I want to contribute but I needed some help ?

**Comment by kabir0x23** [comment]
> hey do you have some relevant resources to start with I want to contribute but I needed some help ?

yes, what kind of help do you need?

**Comment by taran1326** [comment]
I am having difficulty understand how to we imitate this feature

**Comment by kabir0x23** [comment]
> I am having difficulty understand how to we imitate this feature

as of now, u can only focus on frontend design

go to chatgpt, explain this feature , of poll with data in json format for jsx file

const pollData = {}, from here u will get data 

then u use this data to build ui, u can first create ui with dummy data, then use this json data

We will use backend later

**Comment by kabir0x23** [comment]
if u need any help or having doubts feel free to ask below

**Comment by AlexiusTatius** [comment]
Hey @kabir0x23 can I get this issue assigned to me?

**Comment by kabir0x23** [comment]
hey @AlexiusTatius are u working on this issue?

**Comment by AlexiusTatius** [comment]
Sry sir I am not working on this issue

**Comment by AlexiusTatius** [comment]
Sry sir I was not able to work on this issue.

**Comment by ArkadiK94** [comment]
@kabir0x23 is it still in progress?

**Comment by kabir0x23** [comment]
> @kabir0x23 is it still in progress?

yes. it's pending

**Comment by K-21** [comment]
@ArkadiK94 can you assign this to me

**Comment by ArkadiK94** [comment]
@K-21 Hi, how is it going?

**Comment by ArkadiK94** [comment]
@K-21 I am unassign you, tell us if you would like to return to this issue so we will assign you again

**Comment by Tamir198** [comment]
I would like to work on this

**Comment by Tamir198** [comment]
@kabir0x23  Hey I would like to know 2 things : 

1) is there a backend to send the actual request? 
2) where should this poll component be placed? what do you say about inside the common folder?

**Comment by ArkadiK94** [comment]
![Screenshot_20240603_210633_LinkedIn.jpg](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/fd3101f4-dfac-431b-955c-3d4d76779497)

Example for form for this poll 

@kabir0x23 would we want in future to add this poll option in group chat? If so better to make it common, in my opinion. What do you think?

**Comment by kabir0x23** [comment]
no backend for now

not for group chat, i have different thing for that, 

feeds/feedPoll for now

**Comment by ArkadiK94** [comment]
I reopened for the form of poll
@Tamir198 would you like to open new issue about the form for it? If so we could close this issue.

**Comment by ArkadiK94** [comment]
I close this issue. @Tamir198 will open new issue for the left tasks related to poll
