### ISSUE TITLE
[FEATURE] Share Certificate on Social Media option, {branch: dev}.

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#478]
### Detailed description

url: https://www.thecyberhub.org/CTF/certificate/64acb7993afc3c87a96cad7a
local: http://localhost:3000/CTF/certificate/64acb7993afc3c87a96cad7a

![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/d3e20570-c9cc-48f4-9b87-a8e7659618b3)

You can add options: X(twitter),. LinkedIn as of Now

### Context

With this user can share their certificates on social media directly.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tushar-daiya** [comment]
Can i work on this?

**Comment by kabir0x23** [comment]
> Can I work on this?

Yeah sure, if u will have any questions or doubts, feel free to ask here below

Thank you

**Comment by tushar-daiya** [comment]
do we have to share the certificate also as image or just the link to the certificate?

**Comment by kabir0x23** [comment]
> do we have to share the certificate also as image or just the link to the certificate?

yes, we have to do both

**Comment by ArkadiK94** [comment]
@kabir0x23 I saw that pr related to this issue was merged so can we close this issue?
