### ISSUE TITLE
[FEATURE] Community Chat Frontend Only, {branch: dev}.

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#482]
### Detailed description

[🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

Make sure to create a branch from dev branch
Under Dashboard > Community:
![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/a8f5b914-e6cd-47e3-9574-d136704ee74a)

### Context

with this community will stay in network with each other

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsankitbhusal** [comment]
@kabir0x23 what do we need to do exactly, create UI from scratch or fix issues or what?

**Comment by kabir0x23** [comment]
> @kabir0x23 what do we need to do exactly, create UI from scratch or fix issues or what?

We have to include this new feature for chat, kind of discord but only one channel, and only frontend as of now.

**Comment by insane-22** [comment]
Hey @kabir0x23 , I would like to contribute to this issue under Hacktoberfest. Could you please assign this to me?
Thank you for your consideration.

**Comment by kabir0x23** [comment]
> Hey @kabir0x23 , I would like to contribute to this issue under Hacktoberfest. Could you please assign this to me? Thank you for your consideration.

Issue assigned, 

If u will have any doubts or questions, feel free to ask here

thank you.
