### ISSUE TITLE
[BUG] Community Chatbot, {branch: dev}.

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#483]
### Detailed description

We already have a chatbot, but it is not working on a live website, it crashes the main site, so we hide that bot, but now we are thinking of fixing that bot..

### Context

This chatbot will help beginners.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Gabe468** [comment]
May I help with this?

**Comment by kabir0x23** [comment]
Hey @Gabe468, it's in the dev branch, if u are interested, u can give a look

it is only giving error on live website: see https://dev.thecyberhub.org

on local host it is working fine

**Comment by Gabe468** [comment]
I don't see the chatbot in the link in the bottom left

**Comment by kabir0x23** [comment]
> I don't see the chatbot in the link in the bottom left

yeah, because i have commented bot function

error was occurring

when i am running my application in localhost it is working fine, but when i am runnnig it on live domain it is givving me errors, react website, actually i have implement a bot in website after that it is giving issues on live website, but working fine on localhost...

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    ry https://dev.thecyberhub.org/assets/index.50234dbc.js:32
    g https://dev.thecyberhub.org/assets/index.50234dbc.js:30
    Ai https://dev.thecyberhub.org/assets/index.50234dbc.js:32
    zee https://dev.thecyberhub.org/assets/index.50234dbc.js:32
    Pee https://dev.thecyberhub.org/assets/index.50234dbc.js:32
    ppe https://dev.thecyberhub.org/assets/index.50234dbc.js:32
    xv https://dev.thecyberhub.org/assets/index.50234dbc.js:32
    xB https://dev.thecyberhub.org/assets/index.50234dbc.js:32
    Dee https://dev.thecyberhub.org/assets/index.50234dbc.js:32
    E https://dev.thecyberhub.org/assets/index.50234dbc.js:17
    R https://dev.thecyberhub.org/assets/index.50234dbc.js:17
 index.50234dbc.js:32:175

Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    ry https://dev.thecyberhub.org/assets/index.50234dbc.js:32
    g https://dev.thecyberhub.org/assets/index.50234dbc.js:30
    Ai https://dev.thecyberhub.org/assets/index.50234dbc.js:32
    zee https://dev.thecyberhub.org/assets/index.50234dbc.js:32
    Pee https://dev.thecyberhub.org/assets/index.50234dbc.js:32
    ppe https://dev.thecyberhub.org/assets/index.50234dbc.js:32
    xv https://dev.thecyberhub.org/assets/index.50234dbc.js:32
    xB https://dev.thecyberhub.org/assets/index.50234dbc.js:32
    Dee https://dev.thecyberhub.org/assets/index.50234dbc.js:32
    E https://dev.thecyberhub.org/assets/index.50234dbc.js:17
    R https://dev.thecyberhub.org/assets/index.50234dbc.js:17
 index.50234dbc.js:32:49905

**Comment by ArkadiK94** [comment]
@kabir0x23 As I understand it is now a bug issue so I will update this issue accordingly.

**Comment by ash956901** [comment]
can i look into this?

**Comment by kabir0x23** [comment]
> can i look into this?

hi, it's not testable on local, it only crashes on production, 

closing this issue, you can checkout other issues, or create one, thanks
