### ISSUE TITLE
[BUG] In the nav bar section, the icon arrow is not weel aligned with the text

### ISSUE THREAD

**Issue by MaxR522** [thecyberworld/TheCyberHUB#485]
### Describe the bug

As you see in the screen capture bellow, it is not well aligned

### To Reproduce

1. Go to home page and see the navbar

### Expected Behavior

The icon should well aligned with the text

### Screenshot/ Video

![image](https://github.com/thecyberworld/TheCyberHUB/assets/41254151/097c49a5-c3bc-4309-817c-6c44b8936095)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mughalfrazk** [comment]
@MaxR522 if no one is already doing this, id like to have a go here, can you assign this to me

**Comment by MaxR522** [comment]
There is already someone on it

**Comment by kabir0x23** [comment]
> > @MaxR522 if no one is already doing this, id like to have a go here, can you assign this to me
> 
> There is already someone on it

Hey @MaxR522 
want to work on this issue?

**Comment by MaxR522** [comment]
> > > @MaxR522 if no one is already doing this, id like to have a go here, can you assign this to me
> > 
> > 
> > There is already someone on it
> 
> Hey @MaxR522 want to work on this issue?

Yes please

**Comment by MaxR522** [comment]
I already made the Pull Request, this is the link: https://github.com/thecyberworld/TheCyberHUB/pull/486
