### ISSUE TITLE
[FEATURE] Hackbook, {branch: dev}

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#492]
### Detailed description

Resources > Hackbook

This will contains all of the hacking ways, XSS, SQL Injection, etc.

### Context

This feature will be only focused on, how to hack... xss, sqli, etx..

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@kabir0x23 Can we close this issue?
