### ISSUE TITLE
[FEATURE] SecurityBook, {branch: dev}.

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#493]
### Detailed description

This will contains all of the security measurement, 
- How to fix XSS Vulnerability
- How to fix SQL Injection 

### Context

This feature will help the hacker or developers to understand more about security attacks and fixes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@kabir0x23 is it still in progress?
