### ISSUE TITLE
[FEATURE] improvement in home screen of quiz categories 

### ISSUE THREAD

**Issue by priyanshtiwari001** [thecyberworld/TheCyberHUB#496]
### Detailed description

When we visit the quiz section, we are presented with categories or topics to choose from for taking the quiz, and once selected, we can begin the quiz.
 
<img width="1231" alt="Screenshot 2023-10-11 at 1 49 17 PM" src="https://github.com/thecyberworld/TheCyberHUB/assets/64392162/18baabf1-a97c-4734-8f4d-dbcedbd9e168">

### Context

 I propose restructuring the categories section into a card section that will facilitate easy selection of quiz topics and enhance user-friendliness

### Possible implementation

This will make it easier for users to select quiz topics and improve the overall user experience.

<img width="1434" alt="Screenshot 2023-10-11 at 1 53 12 PM" src="https://github.com/thecyberworld/TheCyberHUB/assets/64392162/3f4ee5fc-811b-4460-a940-1e45d28f7955">

After the successfully changing in categories section our topic will be looks like roadmap card.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyanshtiwari001** [comment]
Hi @kabir0x23 , Could you please assign this issue under the hacktoberfast label please.

**Comment by priyanshtiwari001** [comment]
Hi @kabir0x23 , a quick update, I still working on the issue and in next few day i will update you or raise the request.

**Comment by kabir0x23** [comment]
> Hi @kabir0x23 , a quick update, I still working on the issue and find some difficulty. if possible , can you explain me the flow of your site

flow?, can u elaborate it more?

[🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

**Comment by priyanshtiwari001** [comment]
flow, I meant like  how the application is communicating with backend and fetching the data.

**Comment by 0xlarmideh** [comment]
@kabir0x23 has this been resolved?

**Comment by kabir0x23** [comment]
> @kabir0x23 has this been resolved?

it's been a week, i will assign this issue to you.

[🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

**Comment by ArkadiK94** [comment]
@kabir0x23 Can we close the quiz relevanted issues?
