### ISSUE TITLE
[FEATURE] Unix binaries that can be used to bypass local security restrictions in misconfigured systems like GTFO Bins, {branch: dev}.

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#498]
### Detailed description

We can add Unix binaries like 

### Context

This change will be very helpful for pentesters

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
- [ ] give data files more informative names
- [ ] check if there are some improvements to do in design or leave as it is.
