### ISSUE TITLE
CHANGING TO TAILWIND CSS

### ISSUE THREAD

**Issue by Ayusht777** [thecyberworld/TheCyberHUB#500]
### Detailed description

I can Change Some Components to Tailwind Css 

### Context

it is important because most people use it for styling and tailwind is more flexible  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ayusht777** [comment]
ok

**Comment by itsankitbhusal** [comment]
@Ayusht777 I also think that Tailwind will be good but will need to change the whole project code which I think will not be practical.
