### ISSUE TITLE
[FEATURE] Add a new page for - If someone gets scammed, those gov links to help them should be mentioned in that page.

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#501]
### Detailed description

[🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

If someone gets scammed, those gov links to help them should be mentioned in that page.

### Context

This will help those got scammed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aabiskar-dhenga** [comment]
hey mate can u get the figma design of the page

**Comment by kabir0x23** [comment]
> hey mate can u get the figma design of the page

just simple design with links

with description 

> example 

Get scammed?
Images got viral?

when someone click on those title, a page with links and with a small description, how to submit a form/complaint.

**Comment by kabir0x23** [comment]
[🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

**Comment by ezhillragesh** [comment]
Hey @kabir0x23 Can you assign this issue to me I would love to contribute to this issue.
Thanks

**Comment by ezhillragesh** [comment]
Hey @kabir0x23 should I add a new navbar element to take the user to the support pages with links ?

**Comment by kabir0x23** [comment]
> Hey @kabir0x23 should I add a new navbar element to take the user to the support pages with links ? or can I add a new element under the Resources

i think in the resources it will be better

and what can we name that title?

**Comment by ezhillragesh** [comment]
We can Try 'Victim Help'--Guidance and Support for Victim ? is it ok for you

**Comment by kabir0x23** [comment]
> We can Try 'Victim Help'--Guidance and Support for Victim ? is it ok for you

yeah nice

after opening that we will some title like
got scammed? on click, descroipt , links and some steps, like how to do, process
account got hacked? for that we can give that social media help link
images got viral? i thing this also has support, u can get from google

**Comment by ezhillragesh** [comment]
Yeah sure @kabir0x23  I will start working on it.

**Comment by kabir0x23** [comment]
hey @ezhillragesh any updates?

**Comment by ezhillragesh** [comment]
Started already will make a PR asap

**Comment by ezhillragesh** [comment]
The page is blank after running it locally 

![image](https://github.com/thecyberworld/TheCyberHUB/assets/84183052/8350a487-3df4-4511-9a7b-d8f3f2f2401f)
why is this happening? can you help me with it ?

**Comment by kabir0x23** [comment]
> The page is blank after running it locally
> 
> ![image](https://user-images.githubusercontent.com/84183052/282363178-8350a487-3df4-4511-9a7b-d8f3f2f2401f.png) why is this happening? can you help me with it ?

so u haven't started, kay no issues

using different browser will save this issue

**Comment by ezhillragesh** [comment]
> > The page is blank after running it locally
> > ![image](https://user-images.githubusercontent.com/84183052/282363178-8350a487-3df4-4511-9a7b-d8f3f2f2401f.png) why is this happening? can you help me with it ?
> 
> so u haven't started, kay no issues
> 
> using different browser will save this issue

yes , started rn I will make the PR as soon possible, also now its working

**Comment by ArkadiK94** [comment]
@kabir0x23 is it still in progress?

**Comment by ArkadiK94** [comment]
@ezhillragesh I saw that you solved this issue, one problem that was is that instead of creating new branch from dev branch you created from main branch , would you like to try again? 

copy the files to different place in you computer -> move to dev branch -> pull last changes -> created new branch from it -> past the modifications that you did in right places -> create a new pr.

**Comment by ezhillragesh** [comment]
> @ezhillragesh I saw that you solved this issue, one problem that was is that instead of creating new branch from dev branch you created from main branch , would you like to try again? 
> 
> copy the files to different place in you computer -> move to dev branch -> pull last changes -> created new branch from it -> past the modifications that you did in right places -> create a new pr. 
> 

Yeah sure I can do it.

**Comment by ArkadiK94** [comment]
@ezhillragesh one important thing, check to see if your forked repo has dev branch , if not. You should update the repo/ fork it again. You should not creat dev branch you need to use the existing one instead of main.

**Comment by ezhillragesh** [comment]
#673 added a new PR with the correct branch.
