### ISSUE TITLE
[FEATURE] Add a sponsor page.

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/TheCyberHUB#502]
### Detailed description

[🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

example: https://vitejs.dev/
![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/b9dabeea-e4e9-4d30-9895-db9006d6e1e2)

### Context

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shagundubey29** [comment]
Hi, I would like to contribute to this, assigned it to me.

**Comment by shagundubey29** [comment]
Also, are you going to provide figma design?

**Comment by kabir0x23** [comment]
> Also, are you going to provide figma design?

above mentioned design, u can checkout the given url and scroll down u will get it?

free free to ask if u will have any questions or doubts

thank you.

**Comment by kabir0x23** [comment]
and and make sure to checkout the installation guide as well, 

as of now we are working in dev branch, so u have to re-fork it, with all of the branches 

u can follow-up with this [🔨Installation Guide](https://github.com/thecyberworld/TheCyberHUB/tree/dev?tab=readme-ov-file#-installation-guidelines)

**Comment by shagundubey29** [comment]
Okay sure
