### ISSUE TITLE
[FIX]: Change twitter Logo to X Logo

### ISSUE THREAD

**Issue by arnabpal2022** [thecyberworld/TheCyberHUB#514]
### What would you like to share?

The Logo of Twitter needed to be Changed to X as the logo is outdated now,

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
make sure to do in dev branch

**Comment by Draconus524** [comment]
can I work on this issue ?

**Comment by arnabpal2022** [comment]
@kabir0x23 please Check Pull Request #515, And Can you please make this PR under HacktoberFest? It will be helpful.
