### ISSUE TITLE
[DOCS] Change Default Branch To Show Updated README

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#523]
### Description

> > Actually, I was switching to the dev branch, but it was not happening. Otherwise, I have followed the installation guide.
> 
> u have missed the very first step ![image](https://private-user-images.githubusercontent.com/44284877/276582067-9534b18e-b208-47fe-8b77-befa5acdd68a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMjEzMDAsIm5iZiI6MTcwMTAyMTAwMCwicGF0aCI6Ii80NDI4NDg3Ny8yNzY1ODIwNjctOTUzNGIxOGUtYjIwOC00N2ZlLThiNzctYmVmYTVhY2RkNjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDE3NTAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0NjZmYmQ1NDNhZDliMzkzY2YwMzZjNDJhZmI3MDZjMzk5MGQ5NGFhYWRiMDgzYmY2YzU4ZTI2OGJmM2Q5NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x5lbxG2cFo9_Q_M8Br7eSClBuLnY052mDDgHXj11BPE)
> 
> of uncheck that box

I looked over some prs and in pr #508 . You commented that the programmer didn't follow the README.
The problem is when someone new comes to this project they will see the README file which was merged into main branch because the main branch is the default one. 
Two options:
1. Every time that there is a change in Docs , we have to merge it also in the main branch right away
2. Make the dev branch the default one so newcomers will see the updated docs

### Screenshots

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/8c75c38b-d214-43ed-9740-52f8474a8c4e

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
nice, didn't think of that way

thanks for this 👍
