### ISSUE TITLE
[FEATURE] Scrollbar Style Change

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#562]
### Detailed description

There is a grey box in upper side and lower side of the scroll bar. remove it.

<img width="11" alt="Screenshot 2023-12-30 210919" src="https://github.com/thecyberworld/TheCyberHUB/assets/76536506/73c58fba-a7c2-4206-a967-615302691739">

### Context

Better ui style

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sabbirfeni** [comment]
Hey Arkadik,

Hope you are doing well. I am interested on improving scrollbar of the app. Please assign the issue to me.

Best,
Shabbir

**Comment by kabir0x23** [comment]
hi @Sabbirfeni 

i have assigned this issue to you

one thing, not sure u can check, i think this is only comming in chrome, don't know it's bydefault or not

**Comment by Sabbirfeni** [comment]
Okay, I will check this. I will get down to work once I have the chance.

**Comment by ArkadiK94** [comment]
Also, I saw it in Edge browser. Please,  check this browser in addition to Chrome.

**Comment by Sabbirfeni** [comment]
okay

**Comment by Sabbirfeni** [comment]
@ArkadiK94 I have made a PR. Please check out this.

**Comment by ArkadiK94** [comment]
@Sabbirfeni Thanks for your contribution. I close this issue because it was resolved.
