### ISSUE TITLE
Contact form: Form should be user friendly

### ISSUE THREAD

**Issue by Sabbirfeni** [thecyberworld/TheCyberHUB#566]
### Detailed description

Upon closer inspection, I observed a couple of aspects that could be addressed:

1. Lack of Visual Distinction:
The current contact form lacks clear visual cues, such as borders, which could make it challenging for users to distinguish different form fields. This might lead to user confusion and potentially result in input errors.

2. No Focus Borders:
The absence of focus borders makes it difficult for users to identify which form field they are currently interacting with. This lack of visual feedback could cause frustration, particularly for users navigating the form using keyboard inputs.

#Screenshot
![form](https://github.com/thecyberworld/TheCyberHUB/assets/81553366/ee22ce7a-7708-45ba-a0d0-5ef3669e0271)

Proposed Solution:
To optimize the user experience and improve the contact form's usability, I recommend implementing the following changes:

1. Add Clear Borders:
Introduce subtle borders around each form field to provide visual separation and improve the overall readability of the form. This will help users easily identify and navigate through different sections of the form.

2. Include Focus Borders:
Implement focus borders for each form field to indicate the active input area. This visual feedback will guide users through the form, making it more accessible and user-friendly, especially for those using keyboard navigation.

### Context

The form should be easily visible to the users.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sabbirfeni** [comment]
Assign this issue to me.

**Comment by kabir0x23** [comment]
hi, also there is some issues with form, i don't remember exactly

example, if select internship option, and sumbit half details and move to nect option, like feed back, it alerts for missing filds

and u also can check each combinations, if require we can make multiple files, for different option,

**Comment by Sabbirfeni** [comment]
I did not get you. Could you please explain it a bit more.

**Comment by kabir0x23** [comment]
validation issues

![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/71ca172e-fb35-4ff5-9950-f9689dfec59d)

**Comment by kabir0x23** [comment]
@Sabbirfeni do not want to work on this issue?

**Comment by AhmedKarray005** [comment]
hello @kabir0x23 , i have checked the form of the contact page and I want to work on it to make it more user-friendly, also the email is not checked, for example when you type any word even if it is not an email it won't check it for you

**Comment by AhmedKarray005** [comment]
@ArkadiK94 can u answer me please

**Comment by ArkadiK94** [comment]
@kabir0x23 I assigned @AhmedKarray005  because one month has passed from last comment.

**Comment by ArkadiK94** [comment]
@AhmedKarray005 Thanks for your interest to contribute to this. If you will have any questions , you are welcome to ask :)

**Comment by AhmedKarray005** [comment]
@ArkadiK94 yes
Can u please provide more clarification on the issue

**Comment by ArkadiK94** [comment]
@kabir0x23 I don't know a lot about this issue,  could you help him/her?

**Comment by kabir0x23** [comment]
> @ArkadiK94 yes Can u please provide more clarification on the issue

checkout this

https://github.com/thecyberworld/TheCyberHUB/issues/566#issue-2065256639

**Comment by ArkadiK94** [comment]
@AhmedKarray005 Hi, do you work on this issue?

**Comment by AhmedKarray005** [comment]
Hi @ArkadiK94 yes i started working on it , i am late because i have just finished my exams sorry

**Comment by ArkadiK94** [comment]
@AhmedKarray005 It is ok 👍

**Comment by AhmedKarray005** [comment]
@ArkadiK94 , is this okay? 
![Capture d'écran 2024-03-05 124536](https://github.com/thecyberworld/TheCyberHUB/assets/104280658/6c06aa2a-6e28-4998-9269-f7acb5db25ac)

**Comment by ArkadiK94** [comment]
@AhmedKarray005 where is the icon of message? ,in addition, the input box of message is smaller when the upper line.

**Comment by AhmedKarray005** [comment]
I removed the message icon because i did not find it user friendly, for the message box you can scroll down when you write a long message

**Comment by ArkadiK94** [comment]
@AhmedKarray005 make the border right side of message textarea to be align with other elements.

![Screenshot_20240305_175201_Chrome.jpg](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/697a0827-7732-44f0-951f-1c783292e53f)

**Comment by AhmedKarray005** [comment]
@ArkadiK94 
![image](https://github.com/thecyberworld/TheCyberHUB/assets/104280658/8c7d7f98-28f2-45dd-92a0-5e45c31d11c2)

**Comment by ArkadiK94** [comment]
@AhmedKarray005 move the icon a little bit down so it will be in one line with the place holder "message"

**Comment by AhmedKarray005** [comment]
![image](https://github.com/thecyberworld/TheCyberHUB/assets/104280658/b64f184c-4eb4-4cff-9d8f-54aaa32f29bd)
@ArkadiK94

**Comment by ArkadiK94** [comment]
Yup, thank you very much, now, you can create the pr :)
