### ISSUE TITLE
[FEATURE] Mobile Layout, Dispaly SubMenu UI

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#576]
### Detailed description

In layout of mobile, when the menu is open and the user clicks on "Resources" or "Opportunities" find a better way to display the sub-menu.

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/e29a5872-df9a-49ff-94b4-35a6dfc1a0a2

### Context

It looks strange the current opening of the sub menu. 

### Possible implementation

Options to implement:
1. display this tabs under the relative tab
2. open new menu
3. think about a different way and lets discuss 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
> Hi, can I work on this? If yes, please assign it to me.

Yeah sure, 
Thank you

**Comment by ArkadiK94** [comment]
@rakshitriya do you still work on it?

**Comment by Riyazul555** [comment]
Hey @ArkadiK94 I want to work on this issue

**Comment by AbdullahAli420** [comment]
Ok @kabir0x23 this design looks well on pc screen but on mobile screen we have to apply side menu style as applied on [fiverr ](https://www.fiverr.com/) and [upwork](https://www.upwork.com/). (check it)
Adding menu under relative tab will make it more owkward

**Comment by ArkadiK94** [comment]
@AbdullahAli420 Yes, you can do something similar but you don't need to change the direction from where the menu opens and you still can leave the tabs in center, in my opinion. What do you think?

**Comment by AbdullahAli420** [comment]
@ArkadiK94 I tried to implement your idea and result is here. But there are two problems:
1.  I want to add cross(close) icon on the top-right corner of options DropdownContainer but didn't find where it is actually located; (doesn't find it in Navbar.jsx)
2. There is a problem on homepage with navbar. It looks correct on other pages but not on homepage. I will try to fix that.

**Result:**
https://github.com/thecyberworld/TheCyberHUB/assets/118581404/1a9fc556-e5a3-4020-8d15-7ff2e04dc2f6

**Problem on Homepage:**

![Screenshot 2024-03-13 174409](https://github.com/thecyberworld/TheCyberHUB/assets/118581404/2e3b1bbf-22e5-45e5-b684-0c4c1795edc2)
![Screenshot 2024-03-13 174401](https://github.com/thecyberworld/TheCyberHUB/assets/118581404/6388d394-c03e-45dd-89a8-0ee2c5564d8c)

**Any other change you want!**

**Comment by ArkadiK94** [comment]
@AbdullahAli420 I am sorry if I was not clear enough. I liked your idea to do it as in fiverr / upwork , I only said that you should not change the way that the menu is opens , you don't have to open it from left to right, and the place of the main tabs, only add the functionality of the sub-tabs.
I created design for example when we click on "Opportunities" :
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/9595856a-c857-412e-9f3d-6f27a73e7874)

pick which position you prefer more.

**Comment by ArkadiK94** [comment]
in addition. on mobile view, we can rid off the description of sub-tabs

**Comment by ArkadiK94** [comment]
@kabir0x23 what do you think?

**Comment by AbdullahAli420** [comment]
Yes! good idea lets give it a try.
I am trying to implement it. 
I am sorry for late reply. It is due to my exams!

**Comment by ArkadiK94** [comment]
@AbdullahAli420 it is ok, and good luck in the exams

**Comment by ArkadiK94** [comment]
@AbdullahAli420 We are two different persons haha. @kabir0x23 What do you think? I liked it.

**Comment by ArkadiK94** [comment]
@AbdullahAli420 In addition, the gap between main tabs have to be more than the gap between sub tabs.

**Comment by ArkadiK94** [comment]
@AbdullahAli420 you also have to change the icon beside the main tab when you click. When open , it needs to point right, when close point down.

**Comment by AbdullahAli420** [comment]
Ok @ArkadiK94 finally done all 3 changes you want. Result here. Any other changings you want tell me about them!

https://github.com/thecyberworld/TheCyberHUB/assets/118581404/7f027829-6b36-492d-9b4a-abb5adebfd83

**Comment by ArkadiK94** [comment]
@kabir0x23 What do you think?

**Comment by ArkadiK94** [comment]
@AbdullahAli420 no, thank you for your contribution :) ,please create related pr.

**Comment by AbdullahAli420** [comment]
I'm sorry but this is my first contribution to someone else and I don't know exactly what to do after cloning and making changes into files present on my local computer. Please give some guide. I have read [contributing guidelines] (https://github.com/thecyberworld/TheCyberHUB/blob/a7cd9273c44ce674f5d49ec504ff7953bf91dca6/CONTRIBUTING.md) but didn't understand.

**Comment by ArkadiK94** [comment]
ok, which step you didn't understand?
https://www.youtube.com/watch?v=xv9cp7NyK5Y
check this video , if you have specific question I would be happy to help.

**Comment by AbdullahAli420** [comment]
I have tried to do it correctly. If unconsciously any problem occurs sorry for that!
