### ISSUE TITLE
[BUG] Element Over Menu Header

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#590]
### Describe the bug

When you open the console log in the middle of the screen , there is some element that over the main menu so we can't click the tabs in the nav bar.

### To Reproduce

In main page, open console log to the middle of the screen.

### Expected Behavior

find this element and change the styles . you can use the next style example : height: calc(something - something).
or find a different way which we can discuss about.

### Screenshot/ Video

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/df9898cb-d12b-4645-b8e9-ea952cf5eb9f

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jigarBorde** [comment]
Hii, can i work on this issue?

**Comment by ArkadiK94** [comment]
I assigned you, good luck :)

**Comment by kabir0x23** [comment]
@jigarBorde

hi this isssue is comming with sidebar (it is getting opened, (but invisible))

when u decrecres the height of the screen, u will get it, hover with inspect elements
