### ISSUE TITLE
[Style] Align the Text with The Icon

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#597]
### What would you like to share?

In the main page, scroll till the "Contribute To TheCyberWorld" paragraph, there we have 2 buttons , the one with the icon is not aligned in correct way , pls, align it to center.

### Additional information
Screenshots of the paragraph and the button
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/aa009d76-7976-496e-aec1-8d7cab6dbe2a)
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/72b988fa-3686-4b0a-8e6f-053ca9dd156a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PalashChitnavis** [comment]
Hey, can I work on this?

**Comment by PalashChitnavis** [comment]
@ArkadiK94 I have made a PR. Please check it.
