### ISSUE TITLE
[FEATURE] Feeds | Add Filters Of Users 

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#601]
### Detailed description

https://dev.thecyberhub.org/#/feeds

Main page --> Feeds Tab

In the Feeds page add a filter so the user could see all the feeds or only "following users" feeds

### Context

Users could decide to see only feeds of users that they follow after.

### Possible implementation

Think about good place to put the filters. If you have a question, we can discuss.
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/7001c99b-207b-4c84-9ff1-0b1a263f694d)

### Additional information

The "following users" state can be found in src/features/follow , we use Redux.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ben-aoun-1** [comment]
i would like to work on this .

**Comment by Ben-aoun-1** [comment]
can you suggest  how the button should look like ? should it be a toggle ?

**Comment by ArkadiK94** [comment]
@kabir0x23 what do you think? Would there be in the future a need for more than two modes?

**Comment by kabir0x23** [comment]
> @kabir0x23 what do you think? Would there be in the future a need for more than two modes?

no no. two is enough

**Comment by kabir0x23** [comment]
> can you suggest how the button should look like ? should it be a toggle ?
on the top we can show two buttons, 
All | Following

**Comment by Ben-aoun-1** [comment]
How does this look ? 
![image](https://github.com/thecyberworld/TheCyberHUB/assets/147401001/7f903164-8a2a-4fe3-ae50-d436a456e95a)

**Comment by Ben-aoun-1** [comment]
@ArkadiK94 @kabir0x23  any thoughts ?

**Comment by ArkadiK94** [comment]
@Ben-aoun-1 left side feeds, right side functionalities like search. In my opinion, it will look better to put it above the search box. @kabir0x23 what do you think?

**Comment by ArkadiK94** [comment]
Or under the creating new feed block.
