### ISSUE TITLE
[FEATURE] Chat In Dashboard | Connected Users Display

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#602]
### Detailed description

https://dev.thecyberhub.org/#/dashboard/chat

Login --> Dashboard --> Chat

Only show users that are in connection with you in chat search and display
When user is a connection : If user accepted different user's request.

### Context

Users could chat only with users that are connected one with another

### Possible implementation

Need to show under Users only users that you connected with

![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/e84b14b7-ef62-459b-a61f-e0f0008b09c0)

### Additional information

The "connected users" state can be found in src/features/connections, we use Redux.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Navin-nash** [comment]
Can you assign me this?

**Comment by ArkadiK94** [comment]
@Navin-nash do you still work on this issue?
