### ISSUE TITLE
[FEATURE] Profile | Connection Users Buttons Improvments 

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#603]
### Detailed description

Go to any user profile from Explore Tab,
- [ ] if you logged out, and tries to follow someone, will pop up window for login.
@kabir0x23 Where is the pop up for login component located so we could use it here?

- [ ] when someone sends you a request to connect and you go to their profile, you will see more buttons, keep the follow button but move the other two to next line, it overflows to next section.

### Context

Not Logged in visitors would understand why the "follow" button does not works.

About the accept and reject buttons, they overflow to next section.
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/f9fac5ec-bed4-4199-b0e3-d84515bd5506)

### Possible implementation
To see the accept and reject buttons , sign up with another user and click follow the first user.

### Additional information

If you have any suggestion or question don't hesitate to write it :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 92206** [comment]
i have a problem with communicating with the api in my local dev instance and so i cant really test the changes that i made , any reasons why might that be ?

**Comment by kabir0x23** [comment]
> i have a problem with communicating with the api in my local dev instance and so i cant really test the changes that i made , any reasons why might that be ?

can u explain the issue properly

can u attach screenshots?

**Comment by 92206** [comment]
basically anything that consumes data from the backend api isnt working for me  and i get a network error . in explore , feeds etc i get an under maintance screen . i run the project with npm run dev . Have i missed something ? 
![image_2024-01-21_155323734](https://github.com/thecyberworld/TheCyberHUB/assets/75536712/240394e8-22a0-45d7-9abb-c8caf858c63e)

**Comment by ArkadiK94** [comment]
Loggin with username not email, I also had same problem in the beginning.

@kabir0x23 we talked about changing this form to tell users that they should logging with username. I will open an issue about it.

**Comment by 92206** [comment]
> Loggin with username not email, I also had same problem in the beginning.
> 
> @kabir0x23 we talked about changing this form to tell users that they should logging with username. I will open an issue about it.

actually it's a broader problem , as i said even the feed and explore and all other sections that consume the api arent working .
![image](https://github.com/thecyberworld/TheCyberHUB/assets/75536712/45030390-6e92-48ee-bd57-6443b7ff18a2)

**Comment by kabir0x23** [comment]
can u share console error?

**Comment by ArkadiK94** [comment]
Ok, did you created an env file and copied the code from exmple file?
Could you send a screen shot of the folders/files in your local project?

**Comment by kabir0x23** [comment]
okay, nice,  but with commneted these env, u won't able to work on this feature

**Comment by kabir0x23** [comment]
dev env is required to work with this issue

**Comment by 92206** [comment]
i already tried my changes and everything is working fine so far , so i think i will carry on . 

However i need further assistance with one thing , i can't seem to locate the exact component/code snippet responsible for the "Accept /Reject follow request"  

i expect it to be in "UserLinks" next to the follow button but it's not there .

**Comment by ArkadiK94** [comment]
@92206 what is your user name? We will send you a request to connect ,after it, you will see those buttons

**Comment by ArkadiK94** [comment]
https://github.com/thecyberworld/TheCyberHUB/blob/dev/src%2Fcomponents%2FDashboard%2FProfile%2FConnectionsAndFollows%2FConnectionsAndFollows.jsx

**Comment by ArkadiK94** [comment]
The file where this code located

**Comment by kabir0x23** [comment]
> The file where this code src/components/Dashboard/Profile/ConnectionsAndFollows/ConnectionsAndFollows.jsx

this can craash the site, because . in env we have dev api, those contains the features, without env we are connecting with main branch, those does not contain these features

if u get any issues, try to use env

**Comment by ArkadiK94** [comment]
@kabir0x23 He/she tried to use the env file and got cors error. Could it be because the use of Opera browser?

**Comment by kabir0x23** [comment]
> @kabir0x23 He/she tried to use the env file and got cors error. Could it be because the use of Opera browser?

we are also using the same env, sometimes it happend, i am usnig regex over then for whitelisted domain, maybe it took time to understood, i get errors, byt in start only , one time

**Comment by ArkadiK94** [comment]
@92206 Sorry, there is a problem in the back-end with cors, it is not related to you. we will update when it will be resolved.

**Comment by 92206** [comment]
> @92206 Sorry, there is a problem in the back-end with cors, it is not related to you. we will update when it will be resolved.

yeah sure . 
however , related to the first part of the issue : 
![image](https://github.com/thecyberworld/TheCyberHUB/assets/75536712/32b84cb7-e97c-4ee5-a70f-b98cb1462478)

 i have been able to implement the requested task : (for both connect and follow : when not logged in user presses connect or follow the login popup appears  :heavy_check_mark:) 
  
Do you think i can submit a PR for these changes ?

**Comment by ArkadiK94** [comment]
@92206 better to wait with it, and use only dev api. I will update you.

**Comment by ArkadiK94** [comment]
@92206 The problem of cors in backend dev api was fixed, please try again with env config as in example file , update if there are still issues.

**Comment by 92206** [comment]
i no longer get a CORS problem and the communication is established with the dev api . However there's a new issue in explore and feed. 

Here's the console error : 
![image](https://github.com/thecyberworld/TheCyberHUB/assets/75536712/e48e952c-9a19-47c8-9d19-5e2a36a7dfb5)

The problem seems to be originating from this line of code : 
![image](https://github.com/thecyberworld/TheCyberHUB/assets/75536712/91d694be-8e85-4a0c-a9f8-fc5c912223fc)

**Comment by kabir0x23** [comment]
> i no longer get a CORS problem and the communication is established with the dev api . However there's a new issue in explore and feed where the site crashes after loading .
> 
> Here's the console error : ![image](https://private-user-images.githubusercontent.com/75536712/299298536-e48e952c-9a19-47c8-9d19-5e2a36a7dfb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTg1MzcsIm5iZiI6MTcwNjA5ODIzNywicGF0aCI6Ii83NTUzNjcxMi8yOTkyOTg1MzYtZTQ4ZTk1MmMtOWExOS00N2M4LTlkMTktNWUyYTM2YTdkZmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEyMTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMzNiOWFiNzNkNDk3NGM2NDZlNjA1MmM3MjY0YThjYmJjZjIyOGVmOTUyNDEzNTkwNTUyNTk1OGU5OWFjNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qoGMpQESJIwG7WNxEDp9RtjEfp0Lr-CqxzCcSmRSNLQ)
> 
> The problem seems to be originating from this line of code : ![image](https://private-user-images.githubusercontent.com/75536712/299299121-91d694be-8e85-4a0c-a9f8-fc5c912223fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTg1MzcsIm5iZiI6MTcwNjA5ODIzNywicGF0aCI6Ii83NTUzNjcxMi8yOTkyOTkxMjEtOTFkNjk0YmUtOGU4NS00YTBjLWE5ZjgtZmM1YzkxMjIyM2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEyMTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMTFhYjFhOTEyMDcwMWIzOTI2OGY3MGJhMGQ5YzU1ZDRmZDNlYzNmNjBkZTc4NmY2YzhhZWI2MDc0OTlhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ql8xPgBqoWvVPC_ltcSRcmSVlQg1-qY9pPjWW8otCjk)

this issue is with data, if some data is not getting fetched, it will be empty and that's why giving errors, sometime it happens

**Comment by 92206** [comment]
However i see you are placing null checks , shouldnt that help avoid having this error ? #

> > i no longer get a CORS problem and the communication is established with the dev api . However there's a new issue in explore and feed where the site crashes after loading .
> > Here's the console error : ![image](https://private-user-images.githubusercontent.com/75536712/299298536-e48e952c-9a19-47c8-9d19-5e2a36a7dfb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTg1MzcsIm5iZiI6MTcwNjA5ODIzNywicGF0aCI6Ii83NTUzNjcxMi8yOTkyOTg1MzYtZTQ4ZTk1MmMtOWExOS00N2M4LTlkMTktNWUyYTM2YTdkZmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEyMTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMzNiOWFiNzNkNDk3NGM2NDZlNjA1MmM3MjY0YThjYmJjZjIyOGVmOTUyNDEzNTkwNTUyNTk1OGU5OWFjNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qoGMpQESJIwG7WNxEDp9RtjEfp0Lr-CqxzCcSmRSNLQ)
> > The problem seems to be originating from this line of code : ![image](https://private-user-images.githubusercontent.com/75536712/299299121-91d694be-8e85-4a0c-a9f8-fc5c912223fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTg1MzcsIm5iZiI6MTcwNjA5ODIzNywicGF0aCI6Ii83NTUzNjcxMi8yOTkyOTkxMjEtOTFkNjk0YmUtOGU4NS00YTBjLWE5ZjgtZmM1YzkxMjIyM2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEyMTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMTFhYjFhOTEyMDcwMWIzOTI2OGY3MGJhMGQ5YzU1ZDRmZDNlYzNmNjBkZTc4NmY2YzhhZWI2MDc0OTlhOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ql8xPgBqoWvVPC_ltcSRcmSVlQg1-qY9pPjWW8otCjk)
> 
> this issue is with data, if some data is not getting fetched, it will be empty and that's why giving errors, sometime it happens

**Comment by ArkadiK94** [comment]
@92206 I don't get any error, did you sync and update the last commits in your local repo and then git pull the new changes? When you are in dev branch of course.

**Comment by 92206** [comment]
> @92206 I don't get any error, did you sync and update the last commits in your local repo and then git pull the new changes? When you are in dev branch of course.

yes , it's synced .

**Comment by kabir0x23** [comment]
> @92206 I don't get any error, did you sync and update the last commits in your local repo and then git pull the new changes? When you are in dev branch of course.

this issue is with bookmarks data, don't know sometimes this gives errors, like it's fetching data from db
maybe asycn issue is there, 

when data is empty it gives this error, will add some checks here

**Comment by 92206** [comment]
please look into the problem so i can proceed .

**Comment by ArkadiK94** [comment]
@92206 correct me if I am wrong. The file which causes this error not related to this issue. If so, you can try to comment this line or write dummy value , do your changes in the end you should not stage and commit this particular file only your changes which related. Meanwhile we will fix it but it will not stop you to proceed.

**Comment by 92206** [comment]
@ArkadiK94  can you send me a connection request on  @slouma  for testing .
