### ISSUE TITLE
[FEATURE] Explore | Show Only Users That Connected With Current User (you)

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#604]
### Detailed description

https://dev.thecyberhub.org/#/explore

Click Explore Tab

- [ ] add filter for "connections" , "following" , "followers", "all"

### Context

Users could explore the relevant users for them.

### Possible implementation

About All Users : We already have a component of my connections, we can use the same function/design for view all users. 

### Additional information

@kabir0x23 What do you say about making a filter as I wrote upwards?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by LogiqueClergyman** [comment]
Could you please assign this to me? I would love to take a look at this...

**Comment by kabir0x23** [comment]
hi @LogiqueClergyman 

you can get these functions from user profile / connection and follows

**Comment by LogiqueClergyman** [comment]
i am unable to log in. How do i proceed to the chats section?

**Comment by kabir0x23** [comment]
> i am unable to log in. How do i proceed to the chats section?

what's the issue explian

**Comment by ArkadiK94** [comment]
@LogiqueClergyman do you try to login with your email or username. You can login only with username.

**Comment by LogiqueClergyman** [comment]
Sorry, I meant I am unable to register with the website.

**Comment by ArkadiK94** [comment]
@LogiqueClergyman Sorry, there is a problem in the back-end with cors, it is not related to you. we will update when it will be resolved.

**Comment by ArkadiK94** [comment]
@LogiqueClergyman The problem of cors in backend was fixed, please try again , update if there are still issues.

**Comment by ArkadiK94** [comment]
@LogiqueClergyman do you work on this issue?

**Comment by LogiqueClergyman** [comment]
@ArkadiK94 Extremely sorry I missed the notification regarding your comment of the backend CORS issue being fixed. I started working on another project. In the meantime, if anyone else volunteers, feel free to unassign me but I am definitely willing to look into it again as soon as possible.

**Comment by ArkadiK94** [comment]
@LogiqueClergyman It is ok, for now I will unassign you, however, when you will have the time you can ask again to be assigned to this or another issue.

**Comment by sumanjeet0012** [comment]
@ArkadiK94  I want to work on this issue, assign me.
