### ISSUE TITLE
[FEATURE] Quiz section : add answers 

### ISSUE THREAD

**Issue by nassim-ayadi** [thecyberworld/TheCyberHUB#606]
### Detailed description

when we take the quiz , if our answer is right it will skip to the next question ,if the answer is wrong it will show us the right answer (the right answer will be highlighted in green and the wrong one in red ) 

### Context

 Users can benefit from a more educational experience by understanding which questions they answered correctly and learning from those they got wrong. in addition to increasing user engagement. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
hi thanks for creating this issue

**Comment by nassim-ayadi** [comment]
I would like to work on this

**Comment by nassim-ayadi** [comment]
@kabir0x23 did you like how the feature was implemented? Any suggestions or feedback would be awesome!
