### ISSUE TITLE
[FIX FOR DX] antivirus blocking request on the localhost 

### ISSUE THREAD

**Issue by nassim-ayadi** [thecyberworld/TheCyberHUB#613]
### Describe the bug

When attempting to run the project locally, I encounter the following error in the console log:

ShellGenerator.jsx:21 
 GET http://localhost:3000/src/components/Tools/ReverseShell/shellData.jsx net::ERR_ABORTED 499 (Request has been forbidden by antivirus)

### To Reproduce

1 confirm that antivirus software is running 
2 clone the project repository 
3 run the project locally using "npm run dev "
4 open the browser and observe the error 

### Expected Behavior

I expect the project to run without errors.

### Screenshot/ Video

![Capture d'écran 2024-01-24 140329](https://github.com/thecyberworld/TheCyberHUB/assets/150674824/90970470-d41e-443a-bbfa-fd3a80bd64e9)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@kabir0x23 I also has the same problem,  is there a way to solve it? (besides turning off the anti-virus functionality)

**Comment by nassim-ayadi** [comment]
i will look into it

**Comment by kabir0x23** [comment]
> i will look into it

here in that path/file, it contains malicious data templates, it's only templates not real malicious data, it's like dummy data, 

that's why antivirus is alerting it.

**Comment by nassim-ayadi** [comment]
Yes, but what are theese templates ? I know that kaspersky blocks request  from tags named as bank .

**Comment by firassssss** [comment]
i have reproduced this bug i got the same error 
![bug reproduction screenshot](https://github.com/thecyberworld/TheCyberHUB/assets/130941563/de914a03-3e9a-430f-9d63-28048bfda1d2)
does this have to do with some code needed for development ? if so i think this issue should not be considered as a bug .
![Capture d'écran 2024-04-25 231002](https://github.com/thecyberworld/TheCyberHUB/assets/130941563/495dda59-c568-4d90-abeb-061b2257cd36)

**Comment by ArkadiK94** [comment]
@firassssss Yes, It is not a bug but it is something that we should handle in some way. It can scare other developers from contribute to our project.
