### ISSUE TITLE
[BUG] Add Checks For Bookmarks 

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#620]
### Describe the bug

this issue is with bookmarks data, sometimes this gives errors, like it's fetching data from db maybe asycn issue is there,

when data is empty it gives this error, add some checks here

### To Reproduce

src/components/Feeds/FeedPage/FeedPage.jsx

src/components/Feeds/FeedPage/FeedComments/FeedComments.jsx

### Expected Behavior

Add checks so the error will not occur 

### Screenshot/ Video

![299298536-e48e952c-9a19-47c8-9d19-5e2a36a7dfb5](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/c86314ec-a02d-468d-b8e3-4fc82286af19)
![299299121-91d694be-8e85-4a0c-a9f8-fc5c912223fc](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/5dc57852-b4f5-47fa-8a7c-c746f94d87ea)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by git-tirthankar** [comment]
@ArkadiK94 : I created a fix for this issue: https://github.com/thecyberworld/TheCyberHUB/pull/621
Could you check?

**Comment by ArkadiK94** [comment]
Great, thanks for you contribution, I will check the pr shortly.
