### ISSUE TITLE
[FEATURE] Add checkbox/notifications option to user to choose get notified about events and more

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#629]
### Detailed description

We can add in registration time, or in setting to enable it, like a toggle button
all notifications, event notifications etc so users could decide to receive updates and promotions.

### Context

User need to have an option to decide if they want to be notified so it will not be a spam for them and they will have unsubscribe from notifications option.

### Possible implementation

In registration add checkbox
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/56c3a580-03d4-4fa7-9a8a-4daa7768fac0)
and in settings add toggle buttons

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Happyashbunny** [comment]
Hey there I am new to open source and would like to contribute to this feature. It'd be a great help if you could direct me to the folder wherein this need to be implemented and describe the feature a bit further.

**Comment by ArkadiK94** [comment]
### step one:
https://dev.thecyberhub.org/#/register

![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/927aedd5-110e-4ebc-9750-a11ee86998c1)

Currently, when users register they check the "I agree to all statements included in Terms of Use " need to add another check box like in the image 

![302122864-56c3a580-03d4-4fa7-9a8a-4daa7768fac0](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/c8bafd00-9aa1-4592-8f68-def202dd86c0)

@Happyashbunny you can start from step one :)


### step two:
https://dev.thecyberhub.org/#/dashboard/settings/profile
@kabir0x23 in which tab, do you want to add the toggle button so users can turn on / off the option to get updates?

![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/54901b44-8f4a-4342-8c6c-da63760ec8a1)

**Comment by Happyashbunny** [comment]
@ArkadiK94 Thank you for assigning me. I am on it.

**Comment by Happyashbunny** [comment]
@ArkadiK94 I've made a PR #636 please lemme know, if any further changes are to be made.

**Comment by ArkadiK94** [comment]
@Happyashbunny Thanks for your contribution, I will check it shortly and let you know.

**Comment by ArkadiK94** [comment]
@Happyashbunny I reopened this issue for the step two.

**Comment by ArkadiK94** [comment]
>@kabir0x23 in which tab, do you want to add the toggle button so users can turn on / off the option to get updates?

@kabir0x23

**Comment by kabir0x23** [comment]
> > @kabir0x23 in which tab, do you want to add the toggle button so users can turn on / off the option to get updates?
> 
> @kabir0x23

hi

We can do this in two side, events section and settings > notifications section as well

**Comment by ArkadiK94** [comment]
@Happyashbunny would you like to work on this as well?

**Comment by Happyashbunny** [comment]
@ArkadiK94  Sure, I'd be happy to work on this as well. Lemme know what I'm supposed to do.

**Comment by ArkadiK94** [comment]
@kabir0x23 do you have an idea of how to display this section?

**Comment by kabir0x23** [comment]
> @kabir0x23 do you have an idea of how to display this section in settings?

yes, link this

we can do in new iisse 
![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/6ce95612-39a5-4349-8bac-2d5d443cf88d)

**Comment by ArkadiK94** [comment]
@kabir0x23 I am closing this issue because I created a new one for next step
