### ISSUE TITLE
[BUG] Inconsistent Password Length When an symbols is toggled

### ISSUE THREAD

**Issue by ZizouX0** [thecyberworld/TheCyberHUB#634]
### Describe the bug

The Password Generator feature exhibits a bug where the actual length of the generated password does not match the specified length  when the 'Symbols' option is toggled. Specifically, deselecting 'Symbols' results in a password that is only 3 characters long, regardless of the length set by the user. When 'Symbols' is reselected, the password length returns to the user-defined setting

### To Reproduce

go to 'Resources'
go to ' tools'
click on ' Pass Gen'
click on 'symbols'
click on 'Generate'

### Expected Behavior

The generated password should consistently reflect the length specified by the user in the 'Length' option, irrespective of the selection or deselection of 'Symbols'.

### Screenshot/ Video

![image](https://github.com/thecyberworld/TheCyberHUB/assets/147721338/88e866a0-1b2c-456a-a72d-747d621a9b5f)
![image](https://github.com/thecyberworld/TheCyberHUB/assets/147721338/ad260c77-3c85-442e-ac57-6df591ed86ae)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@kabir0x23

**Comment by ZizouX0** [comment]
I will work on it

**Comment by ZizouX0** [comment]
I will work on fixing the bug
