### ISSUE TITLE
[BUG] Limit The Height of Image In Blogs Page

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#642]
### Describe the bug

When the user creates a blog with image of height that is larger than the box it will break other blogs display

### To Reproduce

https://dev.thecyberhub.org/#/blogs
I created an example.

### Expected Behavior

To limit the height or use css in different way so all the blogs will look in normal way.

### Screenshot/ Video

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/bfb3e0a8-a371-4e89-aed1-71b2030f456a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Saifmagouri** [comment]
Hey @ArkadiK94 , when i tried to create a blog it will take me back to the main interface . could you know why ? 
Also faced a problem while communicating with the api in my localhost . So i couldnt test this bug .

**Comment by ArkadiK94** [comment]
@Saifmagouri did you login? To create a blog you need to login first.
When it takes you to the main page , is there some alert on the screen?

**Comment by ArkadiK94** [comment]
@Saifmagouri Could you try again? there was a problem with session expired , we fixed it. See if you can now create new blogs after you login of course.

**Comment by ArkadiK94** [comment]
- [ ] fix it inside the blog as well
