### ISSUE TITLE
[BUG] <White Text Visibility Issue in GoalForm Input>

### ISSUE THREAD

**Issue by Saifmagouri** [thecyberworld/TheCyberHUB#646]
### Describe the bug

When using the GoalForm component in the project, there is an issue with the text color in the input field. The text entered by the user is displayed in white, making it difficult to read against the background.

### To Reproduce

1.Navigate to the page/component where the GoalForm is used.
2.Focus on the input field.
3.Enter some text.

### Expected Behavior

I expect that the user would be able to enter the goal with a clear input text

### Screenshot/ Video

![image](https://github.com/thecyberworld/TheCyberHUB/assets/114822491/0529e860-d160-4c9a-af00-21ed5367dee7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@Saifmagouri Thanks that you found such a bug. Would you like to fix it?

**Comment by Saifmagouri** [comment]
yes i would be glad to do so
