### ISSUE TITLE
Improve SEO and accessibility of home page 

### ISSUE THREAD

**Issue by Sky-De** [thecyberworld/TheCyberHUB#649]
### What would you like to share?

Currently, the home page is not 100% accessible and optimized for SEO.
- [x] I will work on this issue once it has been assigned to me.

### Additional information

![Screenshot 2024-02-10 234106](https://github.com/thecyberworld/TheCyberHUB/assets/79264045/6eb2aef8-4d54-457e-8650-44fe82147794)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sky-De** [comment]
@Tubaleviao 
@indiehjaerta 
@javamultiplex 
Hi, I would like to take on this task and fix the issue. Please assign it to me. Thank you.

**Comment by ArkadiK94** [comment]
@kabir0x23 what do you think?

**Comment by Sky-De** [comment]
@kabir0x23 thanks for the assignment, Could you please inform me of the description you would like to use for the main page of your website? ( Document does not have a meta description )
