### ISSUE TITLE
[FEATURE] Add checkbox/notifications option to user to choose get notified

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#653]
### Detailed description

We need to add it in settings > notifications like a toggle buttons for every thing that the user can be notified about 
all toggle, events toggle,  newsletter toggle, blogs toggle,  and so on.

https://dev.thecyberhub.org/#/dashboard/settings/profile

### Context

Users could have flexibility on the things that they would like to be notified about.

### Possible implementation

This is an example make it for notifications: title "Notifications" , toggle buttons the things that the user could be notified about.
* when the user will register and check the box to get notified the status of all those buttons will be on, and if they will not check the box the default of all will be off.

![303906806-6ce95612-39a5-4349-8bac-2d5d443cf88d](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/28bff7b0-e115-45ff-8546-5e4b439c035d)

### Additional information

@Happyashbunny I created a new issue about this. Do you have some questions about the implementation?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Happyashbunny** [comment]
@ArkadiK94 So later on in the settings section, will there be separate toggle buttons for different kind of notifications or should there just be one that turns all of them on or off at once?

**Comment by ArkadiK94** [comment]
@Happyashbunny both options, a all button, and separate for each notification section

**Comment by Happyashbunny** [comment]
@ArkadiK94 I am not able to register myself, and hence am not able to see the layout of the settings page. I'm probably missing out on something trivial. Can u suggest what I should do? I am bit new to this.

**Comment by ArkadiK94** [comment]
@Happyashbunny do you mean register or login? If login, you should log in with user name and not email. If register, in which step it blocks you?

**Comment by ArkadiK94** [comment]
@Happyashbunny if you get alert of "session expired" every time you try to login, it is a problem from the backend. I will update you when we will resolve this issue.

**Comment by Happyashbunny** [comment]
@ArkadiK94 i was referring to the registration process. I don't receive any code upon submitting my email.

**Comment by ArkadiK94** [comment]
@Happyashbunny check in spam box, the code email go to this box sometimes.

**Comment by Happyashbunny** [comment]
@ArkadiK94 yup found it in spam, thanks for helping me out.
