### ISSUE TITLE
[BUG] fix Search-component adjustments

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#655]
### Describe the bug

We use the Search component in many places in the app. 
In pr #652 , @Som401 created a clear button, it works great in Feeds.
1. However, we use this component in other places in the app , there this button does not work because we need to send the relevant prop to make it work.
2. When we write some text the size of search icon changes , change the style so it will not be affected

### To Reproduce

We use the SearchInputBox in next components:
CTF.jsx --> https://dev.thecyberhub.org/#/ctf
Sidebar.jsx --> https://dev.thecyberhub.org/#/dashboard/chat
NoteSidebar.jsx --> https://dev.thecyberhub.org/#/dashboard/notes
Explore.jsx --> https://dev.thecyberhub.org/#/explore
Feeds.jsx --> here it is working

### Expected Behavior

1. make it work
2. see that the search bar is not moving things around and the size of the search icon is stays the same.

### Screenshot/ Video

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/00ee53ab-de67-434d-9601-8b1df47fde9d

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/82e0f12e-7a55-466b-bc86-9a401239142d

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Som401** [comment]
@ArkadiK94, I've been thinking about expanding the tag-filtering functionality beyond the feeds.jsx file. I believe it would be beneficial to move this functionality to the Search component file. This way, it can be easily accessed and utilized by other components throughout the project like the explore section.

**Comment by ArkadiK94** [comment]
@Som401 Great idea, so users could search multiple words, but wait with making changes in Feeds and FeedPosts files there is a pending pr which make some other changes in those files and I would like to minimize the conflicts that can happen.
