### ISSUE TITLE
[Refactor] Integrate Tag-Filtering Functionality Inside Search Component

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#662]
### What would you like to share?

https://github.com/thecyberworld/TheCyberHUB/issues/655#issuecomment-1941367894
@Som401 wrote in previous issue:
"I've been thinking about expanding the tag-filtering functionality beyond the feeds.jsx file. I believe it would be beneficial to move this functionality to the Search component file. This way, it can be easily accessed and utilized by other components throughout the project like the explore section."

### Additional information

This issue can be implemented only after PR #651 is completed and merged.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Som401** [comment]
sure i'll do it

**Comment by ArkadiK94** [comment]
@Som401 I will let you know when #651 will be merged

**Comment by ArkadiK94** [comment]
@Som401 You can start to work on this issue.

**Comment by ArkadiK94** [comment]
@Som401 if you started, please, merge the updated dev branch into your branch. If you will have some conflicts that you struggle to resolve,  we will help :)
