### ISSUE TITLE
[Style] Public Profile | Fix Fire Icon Place

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#688]
### Describe the bug

Fix fire icon placement 

### To Reproduce

Log in
Go to public profile

### Expected Behavior

The fire icon should be left to number (the number of Streak)

### Screenshot/ Video

![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/e0a391a4-242b-4089-ac98-6982aae92a6b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Riyazul555** [comment]
@ArkadiK94 can you assign me this issue???
I would like to work on it
