### ISSUE TITLE
[FEATURE] Explore First Filter - Option for Non Selected 

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#689]
### Detailed description

In explore, we have the next filter:
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/e96e6a0b-00c3-42d3-ae14-55a2e5323fc0)

### Context

now it is not possible to not select any button.

### Possible implementation

1. when user clicks on Explore the default option should be none selected
2. when user clicks on selected option again it will make it non selected which means -> if none is selected, means "All":
   -  "All" will include all data of the site, because this is an explore where you should have option to find new users content and so on

### Additional information

If you have any question , feel free to ask :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by K-21** [comment]
@ArkadiK94 Can you please assign this to me.
