### ISSUE TITLE
[FEATURE] Explore | Combine all the empty data fields

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#690]
### Detailed description

In Explore, when there are not some data , we will have an block with "Not Found" message, for example if there are not blogs and ctfs we will have something like this:

![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/49be45fb-4e09-4161-97ef-827a2790f8ac)

need to combine to one "Not Found" message

### Context

To much repetitive info

### Possible implementation

minimize all the block texts to one generic that will indicate all the "Not Found", example: User Details, Feeds, Blogs, Not Found (in case there are not user details , feeds or blogs) and if we have Ctfs the "Not Found" message will be blow the Ctf data.

### Additional information

if you have any question , feel free to ask :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Som401** [comment]
@ArkadiK94 Can you assign me this issue.

**Comment by ArkadiK94** [comment]
@Som401 of course with pleasure :)
