### ISSUE TITLE
[Email-Validation]  accepts any form of string (in the internship oppurtunities section)

### ISSUE THREAD

**Issue by iiDaVoDkA** [thecyberworld/TheCyberHUB#695]
### Describe the bug

The contact form currently accepts any string as a valid email, which can lead to submissions with invalid email addresses. This issue proposes adding basic email validation to prevent form submission unless the email address entered by the user matches a standard email format.

### To Reproduce

1. Navigate to the contact form (in the internship oppurtunities section in the first page) 
2. Enter a non-email string in the email input field (e.g., "user@example").
3. Fill out the rest of the form and submit.

### Expected Behavior

*Expected behavior: The form should not submit and should display an error message indicating the email is invalid.
*Actual behavior:The form submits successfully, accepting the invalid email.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@iiDaVoDkA Thanks for creating this issue.

**Comment by iiDaVoDkA** [comment]
i would like to work on it,thanks
