### ISSUE TITLE
[Submitted successfully mechanism] <the form remains in a "submit successfully" state indefinitely>(in the internship opportunities section)

### ISSUE THREAD

**Issue by iiDaVoDkA** [thecyberworld/TheCyberHUB#696]
### Detailed description

After submitting the contact form successfully, the form remains in a "submit successfully" state indefinitely. Users are unable to submit another form unless they reload the page. This behavior could confuse users and prevent multiple submissions from the same session.

Expected behavior: After a successful submission, the form should either reset automatically after a certain period or provide a clear way for the user to reset the form manually.

Actual behavior: The form remains in a "successfully submitted" state with no clear way to reset or submit a new form without reloading the page.

### Context

Improving the form's usability by allowing users to make multiple submissions easily without confusion or the need to reload the page enhances the overall user experience.

### Possible implementation

1.Automatic Reset: Implement a timeout to automatically reset the form state (including the `isSuccess` state) after a successful submission.

.then((response) => {
    if (response.data.message === "Form submitted successfully") {
        setIsLoading(false);
        setIsSuccess(true);
       *new* setTimeout(() => {
            setIsSuccess(false); // Allow the user to submit the form again
        }, 5000); // Reset after 5 seconds
    }
})

2.Manual Reset: Provide a "Submit another response" button that allows users to manually reset the form to its initial state after a successful submission.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@iiDaVoDkA Thanks for creating this issue, would you like to work on it?

**Comment by iiDaVoDkA** [comment]
i would love to work on it

**Comment by ArkadiK94** [comment]
@iiDaVoDkA I think we can go with second approach. In my opinion, if we use a timer users could think that there was a bug so they will submit the same form twice.
