### ISSUE TITLE
[Fix] contact form | fix the form styles to be adaptive for mobile

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#709]
The form is not adaptable to mobile, please, fix it.

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/8bf5dcf2-7beb-46bc-a166-c42f6d6d0541

_Originally posted by @ArkadiK94 in https://github.com/thecyberworld/TheCyberHUB/pull/704#pullrequestreview-1920690928_

**Comment by SinanovicAhmed** [comment]
Hello, I would like to work on this issue.
