### ISSUE TITLE
[FEATURE] Tags & Search Component | selection of tags

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#711]
### Detailed description

Tags & Search Component - 
- remove the link with tags, 
-  make tags active when selected

### Context

more intuitive way.

### Possible implementation

- [ ] remove the link with tags - don't show the name of the tag in search box
- [ ] make tags active when selected - when user select a tag, make it orange (selected one), if multiple tags, make multiple in orange

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DarioTintore** [comment]
Hello, I would like to contribute with this issue :-)

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
Hi, i would like to work on the issue if there is no one working on it

**Comment by AbdullahAli420** [comment]
Hey! @kabir0x23 see this. More than 3 times same error occurred, any solution:
![Screenshot 2024-03-13 055840](https://github.com/thecyberworld/TheCyberHUB/assets/118581404/64538e5f-4e96-45e0-9d26-2dcbf4c3c2d5)

**Comment by AbdullahAli420** [comment]
Hey @kabir0x23 where is that search bar which have to be changed
Tags are already not showing in search box. Where are tags?

**Comment by ArkadiK94** [comment]
https://github.com/thecyberworld/TheCyberHUB/blob/dev/src/components/Common/SearchInputBox/SearchInputBox.jsx
The SearchInputBox component .

https://github.com/thecyberworld/TheCyberHUB/blob/dev/src/components/Feeds/SocialSidebar/Sidebar.jsx
The Sidebar component which contain the tags with searchbox and more elements

- [ ] (In the video) As you can see, when the user clicks on any tag it appears as value in the search-box, we don't want it. We would like to filter by tags but the search box will not contain the tag values. 

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/56f7e348-abe0-4b66-a0ac-c99d93f62d55

- [ ] when we click on tag, it will have different color (orange) and when click again (turn off the filter) will be in regular color (black)
as in linkedin. In addition, the user can select multiple tags so all the activated filters will be in orange.

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/1eac0102-f9f6-4a5e-bf46-c58325edfa18

**Comment by AbdullahAli420** [comment]
Hey @ArkadiK94 I will give my best to achieve this and this time I will not disturb you as earlier.

**Comment by ArkadiK94** [comment]
@AbdullahAli420 how is it going? Do you need some help?

**Comment by ArkadiK94** [comment]
@AbdullahAli420 I unassign you, if you would like to work on it you can ask again.

**Comment by Aaddaammssss** [comment]
can i be assigned this ?

**Comment by Adamss10** [comment]
hello is this still open , i'd like to give it a try .
