### ISSUE TITLE
[BUG] Web Security |  smooth scroll on click on sub topic 

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#715]
### Describe the bug

example: https://dev.thecyberhub.org/#/websecurity/topic/1

Now, when the user clicks on the sub tab, nothing happens

### To Reproduce

Go to Web Security
Go to Topics
Click CSRF 
Click "Introduction to CSRF"
Click on the menu which at the left side
Pick on sub tab
Nothing happens 

### Expected Behavior

When the user clicks on sub topic it will scroll automatically to this place in the section of the text.

### Screenshot/ Video

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/ffdbe3a0-3563-40d3-bcea-7cf3c32782ba

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by K-21** [comment]
@ArkadiK94 can you please assign this to me

**Comment by ArkadiK94** [comment]
@K-21 how is it going?

**Comment by ArkadiK94** [comment]
@K-21 I unassign you.

**Comment by YoussefMlayah** [comment]
https://github.com/thecyberworld/TheCyberHUB/assets/157605627/e9bf6af8-cf1d-4066-9d1b-2664a93b05d9

i ve reproduced this bug , 
can i work on this ?

**Comment by ArkadiK94** [comment]
@YoussefMlayah yes, sure. If you have any question you are welcome to ask :)

**Comment by kabir0x23** [comment]
hi @YoussefMlayah any updates?

**Comment by YoussefMlayah** [comment]
@ArkadiK94 Hi , the work is almost done , sorry didn't see your message
