### ISSUE TITLE
[FEATURE] settings | account

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#716]
### What would you like to share?

![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/0e000b1b-5965-4446-be5f-addf7f22cec1)

@kabir0x23 what should be in this page?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Saifmagouri** [comment]
You can maybe add a Profile Information Update that allow users to update their information or provide a form that allow to change password 
@ArkadiK94

**Comment by ArkadiK94** [comment]
@kabir0x23 what do you think?

**Comment by firassssss** [comment]
i think the settings should have the option to delete the profile/account .

**Comment by ArkadiK94** [comment]
Duplicate issue, see in issue #744
