### ISSUE TITLE
[FEATURE] Chat | Make Chat Visible From Everywhere

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#731]
### Detailed description

Now, the chat component is in dashboard
https://dev.thecyberhub.org/#/dashboard/chat (need to login to access )

move it from there and make it visible from everywhere on the website

### Context

So users could chat from every place

### Do it as in LinkedIn 

close - default the chat will be close (we can discuss about the need of user logo there)
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/799a4841-fa99-43d8-af2f-ae5bb3f12b23)

open - when click on the chat while it is in close state
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/70d7333a-d74b-4dcf-88db-43c8f20ab6c3)

clicked chat - the chat will open in left side and the chat will remain closed until we will click it again
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/9c91e0fd-c865-4f92-9a9a-bbde0ff9affe)

### Additional information

If you have any question you are welcome to ask :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tamir198** [comment]
Would like to take this one, are we talking about this chat?

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/1fd73d49-3d4f-4ba9-9c7b-dc14c017aacd)


Should it look empty? 

@ArkadiK94

**Comment by ArkadiK94** [comment]
@Tamir198 I am sorry, someone already doing it. I will update the issue.
