### ISSUE TITLE
[BUG] Session Expired Error on Sign-In

### ISSUE THREAD

**Issue by yasminebenslim** [thecyberworld/TheCyberHUB#733]
### Describe the bug

When attempting to sign in after creating an account, I encounter a session expired error message. Even after attempting to sign in again, the same error persists.

### To Reproduce

1. Go to the sign-up page.
2. Create a new account.
3. After successfully creating the account, proceed to the sign-in page.
4. Enter the credentials for the newly created account and attempt to sign in.
5. Observe the "Your session has expired. Please login again to continue" error message.
6. Attempt to sign in again.
7. Notice that the same error message appears.

### Expected Behavior

After signing in with the newly created account, the user should be successfully logged in without encountering any session expired errors.

### Screenshot/ Video

![Capture d'écran 2024-04-05 222349](https://github.com/thecyberworld/TheCyberHUB/assets/82983299/e039db1d-ecc5-4c06-a2e0-840854a9eae1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@yasminebenslim Thanks for raising an issue, we will work on it.
