### ISSUE TITLE
[BUG] Number of created blogs stays at 0 in public profile page

### ISSUE THREAD

**Issue by Saifmagouri** [thecyberworld/TheCyberHUB#735]
### Describe the bug

When a user creates a new blog post, the total number of created blogs does not update in the public profile dashboard. Even after creating multiple blog posts, the count remains at 0.

### To Reproduce

Log in to the application.
Navigate to the  public user profile .
Create a new blog post.
Verify that the blog post is successfully created.
Return to the user .
Note that the total number of created blogs remains at 0.

### Expected Behavior

After creating a blog post, the total number of created blogs in the public profile dashboard should increase to reflect the newly created post.

### Screenshot/ Video

![image](https://github.com/thecyberworld/TheCyberHUB/assets/114822491/45298dbe-dabd-4793-ba33-4481fe1f209b)
![image](https://github.com/thecyberworld/TheCyberHUB/assets/114822491/76345819-ac26-4368-8b80-51419a280c22)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@Saifmagouri Thanks for raising this issue, would you like to work on it?

**Comment by Saifmagouri** [comment]
yes i would like to @ArkadiK94

**Comment by ArkadiK94** [comment]
@Saifmagouri if you have any questions you are welcome to ask :)

**Comment by Saifmagouri** [comment]
@ArkadiK94 where can i find the path of the backend in the project ?

**Comment by ArkadiK94** [comment]
src/features/blogs/blogSlice.js

Redux of blogs

**Comment by Saifmagouri** [comment]
when you save the blog is there a database in the local host ? and is every blog saved with the api or with the backend that is integrated in the local ? @ArkadiK94

**Comment by ArkadiK94** [comment]
@Saifmagouri frontend connected to backend with restful api . We get the data and store in redux.

**Comment by Saifmagouri** [comment]
Can you send the backend that you have in your server because i want to change the code in backend . @ArkadiK94

**Comment by ArkadiK94** [comment]
@Saifmagouri nope, you can't have access to the backend. If the issue require a backend changes you can say what you want and we will change accordingly.

**Comment by Saifmagouri** [comment]
![image](https://github.com/thecyberworld/TheCyberHUB/assets/114822491/72c1d381-b8e5-48a6-8e30-64cae90674f2)

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>YJQ258Y7SMTRAC6V</RequestId>
<HostId>sEZBgs2btjtnto2etZ88gar0Ymu6bdW0XqMmoOW/e5a5Pt4rPFeABxKTaZrz44IETZCBS7OEdys=</HostId>
</Error>
this is the error that i faced 
i want to discover what is inside the backend to fix it

**Comment by kabir0x23** [comment]
can u share access denied screenshot with req/response? @Saifmagouri

**Comment by kabir0x23** [comment]
no backend required, there is small mistake in logic
in blogs : blogCount 

 u can check out that

**Comment by Saifmagouri** [comment]
everytime i add a blog in my profile it doesnt change 
![image](https://github.com/thecyberworld/TheCyberHUB/assets/114822491/206fd39f-32e1-49f3-afc5-99ae695fd845)

**Comment by Saifmagouri** [comment]
![image](https://github.com/thecyberworld/TheCyberHUB/assets/114822491/14b35267-06be-4665-b946-a8ec18da93af)
this is another problem regarding the image 
@kabir0x23

**Comment by kabir0x23** [comment]
> ![image](https://private-user-images.githubusercontent.com/114822491/322204468-14b35267-06be-4665-b946-a8ec18da93af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMTAzNzcsIm5iZiI6MTcxMzAxMDA3NywicGF0aCI6Ii8xMTQ4MjI0OTEvMzIyMjA0NDY4LTE0YjM1MjY3LTA2YmUtNDY2NS1iOTQ2LWE4ZWMxOGRhOTNhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QxMjA3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWZiY2I2ZTg3NzYyNDBkZjUwOTZmNmFlNTBjMDlmYjhhNjM5NGViOTUwY2YwMGVhOWE3NTQ4OGM3Yjc5ODJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HTEeMi2Ok-YFK6nSEsyeqxVs578g6f4YdlcKLl0xr18) this is another problem regarding the image @kabir0x23

can u send full screenshot, from where u are getting access deined

**Comment by Saifmagouri** [comment]
![image](https://github.com/thecyberworld/TheCyberHUB/assets/114822491/126e8458-a9b9-43f8-a64f-f1f6cd77827e)
![image](https://github.com/thecyberworld/TheCyberHUB/assets/114822491/63e98a21-135b-4e44-935f-86a78abdd785)

why it the variable blogcount changed from 38 to 0 . that is the problem 
@kabir0x23

**Comment by kabir0x23** [comment]
console log blog data nd userdetail, u will see there is not username in blog

---

u can check common this in blog and userdetials and change iit in blog cout, it will work.

i have fixed, example. u can fix and push cahnge
![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/5e652aba-4b33-4277-8188-9a92708d5a29)

**Comment by Saifmagouri** [comment]
what do you mean by  check common or if you can just send me the code line of the problem @kabir0x23 thank you

**Comment by ArkadiK94** [comment]
@Saifmagouri thanks for raising the issue, @kabir0x23 will push the changes as he solved it.
if you would like to work on different issue you are welcome.
