### ISSUE TITLE
[FEATURE] Update Twitter Logo to New "X" Logo in Media Links Button

### ISSUE THREAD

**Issue by nassim-ayadi** [thecyberworld/TheCyberHUB#740]
### Detailed description

The project currently uses the outdated Twitter logo in the media links button. To keep the website up to date and ensure a modern user experience, it's essential to replace the old logo with the new "X" logo. This update will align the project's visuals with current standards and maintain consistency across online platforms.

### Context

The media links button provides users with access to the project's social media profiles. However, the use of the outdated Twitter logo creates a discrepancy between the website's appearance and current branding trends. Updating the logo to the new "X" logo will help maintain a contemporary look and feel for the website.

### Possible implementation

Replace the existing Twitter logo asset with the new "X" logo asset in the project's codebase.
Update any references or links to the Twitter logo to point to the new "X" logo.
Ensure proper display of the new logo across different devices and screen sizes.
Conduct thorough testing to verify that the logo update does not introduce any layout or functionality issues.
![Capture d'écran 2024-04-18 121517](https://github.com/thecyberworld/TheCyberHUB/assets/150674824/723a4511-850a-4bea-8f75-0a3ae7acf1e6)
![Capture d'écran 2024-04-18 121503](https://github.com/thecyberworld/TheCyberHUB/assets/150674824/551dd5a6-6f84-46dc-8e39-38ee99923712)

### Additional information

Obtain the new "X" logo from official Twitter resources or other reliable sources.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
https://dev.thecyberhub.org/

You should check on the dev website.
It already was updated so I close this issue.
