### ISSUE TITLE
add a profile detail page 

### ISSUE THREAD

**Issue by ZizouX0** [thecyberworld/TheCyberHUB#742]
### Detailed description

i think that we should add a profile details page in which you can view and edit  personal details like password , email ect 

### Context

-Trust and Transparency: Allowing users to see and manage their information can build trust.
-In addition to that over time, personal details may change. Providing users with the ability to update their information ensures that the data remains accurate and up-to-date, which is essential for any services that rely on this information. Overall i can tell that It empowers users by giving them direct control over their personal information. This feature enhances user experience by making it easy to update information

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
![Screenshot_20240419_011128_Chrome.jpg](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/19a1d881-42b0-4e7f-9758-84e5f218796a)

Settings > Profile 

We need to create the other pages in settings if you would like to work on one of the pages create new issue and we can discuss :)

**Comment by ArkadiK94** [comment]
I close this one
