### ISSUE TITLE
[FEATURE] settings | Add Account page 

### ISSUE THREAD

**Issue by ZizouX0** [thecyberworld/TheCyberHUB#744]
### Detailed description

For the account component in the settings we can add
1.	Profile Picture: Allow users to upload a profile picture to personalize their account.
	2.	Account Activity: Provide a section where users can see their recent activity, like logins and changes made to the account.
	3.	Privacy Settings: Include options for users to control who can see their profile or specific parts of their profile.
	4.	Connected Apps: Show a list of apps and services that the user’s account is connected to, with options to manage these 
	5.	Notification Preferences: Allow users to customize how and when they receive notifications.
	
	6.	Account Deletion: Give users the option to delete their account, along with clear information about what that means for their data. 

### Context

Well in my opinion Adding these features to an account page enhances user engagement by enabling personalization through profile pictures and customizable notifications. Transparency and security are boosted with visible account activity and manageable connected apps. Privacy settings empower users to control their data visibility, fostering trust. The straightforward account deletion option underscores user autonomy over their data, aligning with best practices in data protection. Overall, these improvements significantly enhance user satisfaction and confidence in the platform.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@kabir0x23 what do you think?

**Comment by ArkadiK94** [comment]
![Screenshot_20240426_235136_GitHub.jpg](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/c7f33629-4082-43d9-8fd7-535b6e1232ca)

I am putting it here from a duplicate issue and I will close the other issue.

**Comment by Salem-Bourguiba** [comment]
Is the backend functionality for deleting user accounts operational?

**Comment by ArkadiK94** [comment]
@kabir0x23 what do you think? Do we can delete user? Is it something that we should add?
In addition, what do you think about the other suggestions?

**Comment by kabir0x23** [comment]
For the account component in the settings we can add

>   1.  Profile Picture: Allow users to upload a profile picture to personalize their account.
we already have this

>  2. Account Activity: Provide a section where users can see their recent activity, like logins and changes made to the account.
this one too, ,but it;'s in backend for now

> 3. Privacy Settings: Include options for users to control who can see their profile or specific parts of their profile.
> 4. Connected Apps: Show a list of apps and services that the user’s account is connected to, with options to manage these
good idea

>     5. Notification Preferences: Allow users to customize how and when they receive notifications.
already have this

> 6. Account Deletion: Give users the option to delete their account, along with clear information about what that means for their data.
we have this but only in backend for now
