### ISSUE TITLE
[BUG] <description> Filtering Blog by tags 

### ISSUE THREAD

**Issue by Adamss10** [thecyberworld/TheCyberHUB#745]
### Describe the bug

When i click on a tag in blogs page , the app crashes 

### To Reproduce

1. Go to "Blogs"
2. Click on any tag to filter the blogs 
3. the app crashes with error in image below : 
![image](https://github.com/thecyberworld/TheCyberHUB/assets/131713490/ea2189ac-915a-4015-ab57-9cb3af668e68)

### Expected Behavior

The blogs are filtered by tag 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@Adamss10 Thanks for raising this issue, would you like to fix it?

**Comment by Adamss10** [comment]
> @Adamss10 Thanks for raising this issue, would you like to fix it?

Sure , i'm almost finished with #711 ,   so maybe ill introduce the fixes there since the issues are somewhat related ?
