### ISSUE TITLE
[BUG] Code of conduct not found

### ISSUE THREAD

**Issue by Tamir198** [thecyberworld/TheCyberHUB#749]
### Describe the bug

When you open a new pr you are suggested to go to the code of conduct, currently its not found

### To Reproduce

Open new pr, you will see this : 

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/3ddad133-93c4-45ae-a8f8-87f72d0027b6)

### Expected Behavior

The link should redirect to the project code of conduct

### Screenshot/ Video

Instead, this is what we see : 

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/bbea007d-a144-4cf9-a819-2894af25b104)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tamir198** [comment]
I would like to take this issue, is this `https://github.com/thecyberworld/TheCyberHUB/blob/dev/CODE_OF_CONDUCT.md` the place where we would get redirected instead?

**Comment by ArkadiK94** [comment]
@Tamir198 Yes, need to change from "main" to "dev" in all the templates. Thanks for raising this issue 😁
