### ISSUE TITLE
[Bug report] <Non-functional Buttons on Website>

### ISSUE THREAD

**Issue by yasminebenslim** [thecyberworld/TheCyberHUB#752]
### Detailed description

The buttons for 'About', 'Services', 'Community', and 'Forum' on the website are currently non-functional. When clicked, they do not navigate users to the corresponding pages as expected.

### To Reproduce

1. Visit the website.
2. Locate the buttons for 'About', 'Services', 'Community', and 'Forum'.
3. Click on any of the mentioned buttons.
4. Notice that the button does not lead to the expected page

### Expected Behavior

The buttons for 'About', 'Services', 'Community', and 'Forum' should be clickable and properly navigate users to the corresponding pages.

### Screenshot/ Video of the Responsive Problem

https://github.com/thecyberworld/TheCyberHUB/assets/82983299/3959c8e4-a971-411d-9310-e74a6a9e4791

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@yasminebenslim hi, you entered the main website. Please, check it in the dev environment.
https://dev.thecyberhub.org/

**Comment by ArkadiK94** [comment]
After it, you should modify the issue accordingly

**Comment by ArkadiK94** [comment]
@yasminebenslim I will close it for now and you could reopen or create different one when you will check in the right url.
