### ISSUE TITLE
[BUG] Verification email is being send to the spam folder

### ISSUE THREAD

**Issue by Tamir198** [thecyberworld/TheCyberHUB#754]
### Describe the bug

Not sure if it's only for me, but when I created a new user the verification code was sent to my spam folder.

### To Reproduce

To reproduce create a new user and check where the verification code is inside your mail.

### Expected Behavior

Expect to not go to the spam folder

### Screenshot/ Video

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/a844cbaa-de16-40c6-ae58-def9e4579750)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@Tamir198 It is not only for you.
Do you have any suggestions how to solve it?

@kabir0x23 is there something to do with it?

**Comment by firassssss** [comment]
i have created an account in both the website and the Development Website . an the email was sent to my email inbox accordingly
(not the spam) . i ama using Gmail . maybe this bug is affected by the Email Service Provider the user is using .

**Comment by ArkadiK94** [comment]
@firassssss I am also using Gmail but I got this email in spam folder a few times so far.

**Comment by kabir0x23** [comment]
> @firassssss I am also using Gmail but I got this email in spam folder a few times so far.

for some people it is going in inbox but for some in spam, have to check

and will also add a message in alert, if u didnt revice the mail, u check your spam folder as well.
