### ISSUE TITLE
[BUG]  api key wrong printing?

### ISSUE THREAD

**Issue by Tamir198** [thecyberworld/TheCyberHUB#755]
### Describe the bug

in settings/api under the "your api key" looks like this : 

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/7499bf8e-5aad-4e2d-8bb1-50f5c98b2c5b)

Is this a mistake? this is the default `object.toString` of js.

### To Reproduce

Log in and go to the settings/api

### Expected Behavior

I am not sure about the expected behavior, should it be "default value" or maybe "no key yet" (created this inside a new account) 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@Tamir198 the value should be empty and only the placeholder should be visible.
Would you like to work on it?

**Comment by ArkadiK94** [comment]
@Tamir198 the value should be empty and only the placeholder should be visible.
Would you like to work on it?

Unless we get the api key from backend or the user enters it

**Comment by Tamir198** [comment]
Sure i would like to work on it - so it I have API key display it and if not display the placeholder ye ?

**Comment by Tamir198** [comment]
@ArkadiK94  I cant seem to reproduce this problem, it looks like this was a one time problem.

**Comment by ArkadiK94** [comment]
![Screenshot_20240429_160342_Firefox.jpg](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/80af7cf3-4ff9-4324-abd9-b89652792853)

From mobile, sign out -> sign in -> open settings/api and wait few seconds -> it will appear again

**Comment by Tamir198** [comment]
From what browser are you logged in? Using pc with chrome latest this is not happening to me

**Comment by Tamir198** [comment]
Yeah, I think I submitted an API key. How can I remove it so I can have a new user experience : 

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/6b1ed421-1712-43d6-a430-8529a7d1e7f8)

**Comment by ArkadiK94** [comment]
@Tamir198 1. Create new user, 2. Leave this issue and someone else will handle it, you can continue to different issue.

**Comment by Tamir198** [comment]
I think I would rather leave this to someone else, I don't want to start opening accounts if I submit by mistake. 
Thank you
