### ISSUE TITLE
[BUG] Add new goal could be submited empty

### ISSUE THREAD

**Issue by Tamir198** [thecyberworld/TheCyberHUB#756]
### Describe the bug

I can submit a new goal with an empty title : 
Should we force a non empty title? 

### To Reproduce

Log in and go to settings/goals

### Screenshot/ Video

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/10f48c46-007a-4424-a235-738b2795da16)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tamir198** [comment]
Yes thank you, I will work on this and on the other issue for now.

**Comment by firassssss** [comment]
after submitting the goal .the goal card does not match the general website styling , should i make an issue about it ?

**Comment by ArkadiK94** [comment]
@firassssss yes, you can.
