### ISSUE TITLE
[BUG] Filters in Web security page 

### ISSUE THREAD

**Issue by 92206** [thecyberworld/TheCyberHUB#758]
### Describe the bug

The indicator color for selected filter is applied during hover only, after i select the filter and move the cursor the orange color doesnt persist .

### To Reproduce

1. Go to Web Securit page
2. Click on any of the tabs there (Topic - web labs ...)
3. Click on any of the filters in the left section 
4. the filter applies but the there's no visual indicator (no orange color on the selected filter  )

### Expected Behavior

The selected filter has a differentiating color that would persist even after hovering on the filter 

### Screenshot/ Video

![image](https://github.com/thecyberworld/TheCyberHUB/assets/75536712/d4f2749c-18b8-44e6-ab85-d47ff22bc34d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@92206 Thanks, would you like to handle this bug?

**Comment by seifnamissi** [comment]
I would like to work on this if it's okay with you @92206  ?

**Comment by 92206** [comment]
sure , please go ahead .

**Comment by seifnamissi** [comment]
Great ! @ArkadiK94  can i be assigned ?
