### ISSUE TITLE
[FEATURE]  Improve Dashboard UX ,Enable Profile Avatar Navigation

### ISSUE THREAD

**Issue by firassssss** [thecyberworld/TheCyberHUB#759]
### Detailed description

Currently, clicking on the profile picture avatar in the dashboard does not trigger any action. This feature proposes to enhance user experience by implementing functionality that redirects the user to their public profile page upon clicking their avatar.
![Capture d'écran 2024-04-25 225454](https://github.com/thecyberworld/TheCyberHUB/assets/130941563/25794c95-9dbb-468d-87ae-5dc2ffd5e0a0)

### Context

Users often navigate between different sections of the application, including the dashboard and their public profile. Adding a direct link from the dashboard's profile avatar to the user's public profile reduces the number of clicks required to access their profile information, improving overall usability.

### Possible implementation

Add an onClick event handler to the profile avatar component.
Implement routing logic to redirect the user to their public profile page.

### Additional information

Implementing this feature streamlines user navigation and aligns with modern web application standards, enhancing the overall user experience.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@firassssss Thanks, would you like to handle it?

**Comment by firassssss** [comment]
yes
