### ISSUE TITLE
[FEATURE] Enhance Visual Presentation of Goal Card Component

### ISSUE THREAD

**Issue by firassssss** [thecyberworld/TheCyberHUB#760]
### Detailed description

The current implementation of the goal card component lacks visual styling, making it less appealing and impactful for users. To enhance the overall user experience and improve engagement, it's essential to style the goal card component to make it visually appealing and aligned with the design aesthetics of the platform.
![goal styling](https://github.com/thecyberworld/TheCyberHUB/assets/130941563/92c3e801-5449-461b-b2c4-5600b416da05)

### Context

he goal card component serves as a crucial element in providing users with a clear overview of their goals and progress. A well-styled goal card not only improves the visual appeal but also reinforces the importance of goal tracking and achievement.

### Possible implementation

Add appropriate styling, including but not limited to background colors, borders, and typography, to the goal card component.
Ensure consistency with the platform's design system to maintain visual harmony across different sections.
Incorporate visual indicators or icons to highlight important information such as goal status, progress, and due dates.
Optimize spacing and layout to improve readability and usability of the goal card on various devices and screen sizes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@firassssss seems very needed, do you want to handle it?

**Comment by Salem-Bourguiba** [comment]
can I work on it ?

**Comment by ArkadiK94** [comment]
@firassssss is it ok that he/she will work on it?

**Comment by firassssss** [comment]
@ArkadiK94 yes i am ok with it

**Comment by ArkadiK94** [comment]
@Salem-Bourguiba yes, you can work on it

**Comment by Salem-Bourguiba** [comment]
i need some feed back i am i going in the right tracks 
![Capture d'écran 2024-04-27 005315](https://github.com/thecyberworld/TheCyberHUB/assets/157995342/239f3ab6-9d28-42ba-8d8b-d1a829dededd)

**Comment by ArkadiK94** [comment]
@Salem-Bourguiba Looks awesome 😎

**Comment by Salem-Bourguiba** [comment]
can we use different styles for a component used in different components ?
exemple : can he set a styling for the popUpWindow in component1 with out effecting the styling of the PopUpWindow in component2 ?
how does this work ?

**Comment by Salem-Bourguiba** [comment]
should i add a plus sign in the end of the input bar ? or add a goal placement is fine ?

**Comment by ArkadiK94** [comment]
@Salem-Bourguiba we can "add goal" button so I think it is enough but if you have a different proposal that you think will look better we can discuss

**Comment by Salem-Bourguiba** [comment]
![Capture d'écran 2024-04-27 131332](https://github.com/thecyberworld/TheCyberHUB/assets/157995342/b667e0d8-df53-47ef-8d3d-930b8a20f99c)
like this maybe ?

**Comment by ArkadiK94** [comment]
@Salem-Bourguiba The "add goal" button is more intuitive in my opinion.
@firassssss What do you think?
@kabir0x23 What do you think?

**Comment by firassssss** [comment]
> @Salem-Bourguiba The "add goal" button is more intuitive in my opinion. @firassssss What do you think? @kabir0x23 What do you think?

i think i serves its purpose better than "add a goal" , think he should keep the + sign

**Comment by ArkadiK94** [comment]
@Salem-Bourguiba I am ok with the '+' sign so place it outside of the input box at least

**Comment by Salem-Bourguiba** [comment]
ok .should i create a pull request ?

**Comment by ArkadiK94** [comment]
@Salem-Bourguiba Yes, you don't need to ask when to create a pull request, you should do it when you feel that the code is ready for review.
Unless, you want to ask something particular about the code or show progress so you can create draft pr, fyi :)

**Comment by Salem-Bourguiba** [comment]
![Capture d'écran 2024-04-27 135845](https://github.com/thecyberworld/TheCyberHUB/assets/157995342/768096f8-b3ae-4f7d-a6f1-c9ddcd127748)
i think this implementation is much better than just throwing the + sign in the input field 
it's more orgenized and clear like this plus it has a hover effect to indicatee the clickable button
