### ISSUE TITLE
[FEATURE] Analytics | Add Functionality For Analytics Page

### ISSUE THREAD

**Issue by Tamir198** [thecyberworld/TheCyberHUB#769]
### Describe the bug

Under setting -0> Analytics there is a Most Active Times graph and it got a Hours button that some seem to be click able

### To Reproduce

Go to dashboard -> Analytics tab

### Expected Behavior

Expected tat the button will be clickable

### Screenshot/ Video

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/b039d99a-ba3f-4f89-a4a6-f74fd2ca838e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@Tamir198 All this page is not functional 

Would you like to work on all the functionality of this page?

If you have questions, you are welcome you ask :)

**Comment by Tamir198** [comment]
Ye sure, let's start from where I get the data to the house maybe?

**Comment by kabir0x23** [comment]
> @kabir0x23 did someone implement the backend? Or should he create a dummy data json file for now?

dummy is fine for now, backend is not done yet,

**Comment by Tamir198** [comment]
@kabir0x23 @ArkadiK94 
 Do you want me to decide on the structor for the data? and later on, we can refactor it into the backend data?

**Comment by ArkadiK94** [comment]
@Tamir198 yes, if you will have questions about the structure you can ask.
