### ISSUE TITLE
[FEATURE] quiz | the "next question" button - modifications

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#772]
> I know it just the design of the button is always at the right bottom that's what people are used of in this case it is a "next" button .So i think that we can add the "show answer " button on that side for an optimal user experience .

_Originally posted by @ZizouX0 in https://github.com/thecyberworld/TheCyberHUB/issues/632#issuecomment-2082117842_

The "nextQuestion" button is on top.
1. change the text to "next question" 
2. let's discuss if to leave it on top or move it to under the possible answers in the bottom.

@kabir0x23 what do you think?

![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/f38467ea-77b6-4af8-b81d-fde0559af891)

**Comment by AhmedKarray005** [comment]
hello @ArkadiK94 , assign me to this issue

**Comment by ArkadiK94** [comment]
@AhmedKarray005 it is in discussion phase.
@kabir0x23 what do you think? should we implement it?

**Comment by AhmedKarray005** [comment]
@kabir0x23 ????

**Comment by kabir0x23** [comment]
yes, good idea

**Comment by ArkadiK94** [comment]
@ZizouX0 Thanks for the idea.
@AhmedKarray005 I will assign you.

**Comment by AhmedKarray005** [comment]
@ArkadiK94 you want the button under the possible answers in the bottom.

**Comment by ArkadiK94** [comment]
@AhmedKarray005 yes

**Comment by AhmedKarray005** [comment]
@ArkadiK94 
![image](https://github.com/thecyberworld/TheCyberHUB/assets/104280658/0cbb7405-8479-4cb1-91d0-ba1f85493a78)

**Comment by ArkadiK94** [comment]
@AhmedKarray005 Looks great 👍

**Comment by kabir0x23** [comment]
looks good

**Comment by ArkadiK94** [comment]
@AhmedKarray005 did you created pr for this issue?

**Comment by AhmedKarray005** [comment]
@ArkadiK94 yes
