### ISSUE TITLE
[FEATURE] Interview-Questions

### ISSUE THREAD

**Issue by seifnamissi** [thecyberworld/TheCyberHUB#775]
### Detailed description

In interview questions page when you select a topic it does not have a visual indicator that it is selected .

### Context

It's confusing to not know which element is selected 

### Possible implementation

the selected topic is highlighted in orange 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seifnamissi** [comment]
i would like to fix this

**Comment by ArkadiK94** [comment]
@seifnamissi could you add screenshot/short video?

**Comment by seifnamissi** [comment]
[Uploading screen-recorder-fri-may-03-2024-20-49-21.webm…]()

**Comment by seifnamissi** [comment]
[screen-recorder-fri-may-03-2024-20-49-21.webm](https://github.com/thecyberworld/TheCyberHUB/assets/152433554/32a180af-d1ec-4dbe-8636-03f8376bdf94)

**Comment by ArkadiK94** [comment]
@seifnamissi please, sync the new changes.
It was already implemented in yesterday's merge, so I close this issue.

![Screenshot_20240503_225901_Firefox.jpg](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/411605b3-2d99-4442-9c53-c234422902fb)

**Comment by ArkadiK94** [comment]
@seifnamissi By the way, thanks for trying :)

**Comment by ArkadiK94** [comment]
@seifnamissi I checked from mobile, weird , in mobile it works, but on desktop not. Would you like to handle this?

**Comment by seifnamissi** [comment]
yes , i'll handle it .

**Comment by ArkadiK94** [comment]
@seifnamissi Thanks :)
