### ISSUE TITLE
[FEATURE] Add Show Password Option

### ISSUE THREAD

**Issue by AhmedKarray005** [thecyberworld/TheCyberHUB#779]
### Describe the bug

When a user enters an incorrect password in the password field, the field does not automatically clear itself. Instead, the incorrect password remains in the field until manually deleted by the user.

### To Reproduce

Navigate to the login page.
Enter an incorrect password in the password field.
Observe that the incorrect password remains in the field.

### Expected Behavior

After entering an incorrect password, the password field should automatically clear itself, ready for the user to re-enter their password without having to manually delete the incorrect input.

### Screenshot/ Video
![Uploading image.png…]()

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@AhmedKarray005 If we would have "show password" it is not relevant.

@kabir0x23 what do you think?

**Comment by ArkadiK94** [comment]
@AhmedKarray005 You don't need to clear input if we have show password so the user could change typo and so on.
Let's wait @kabir0x23 to hear his opinion

**Comment by AhmedKarray005** [comment]
@kabir0x23 ??

**Comment by AhmedKarray005** [comment]
@kabir0x23

**Comment by kabir0x23** [comment]
hey @AhmedKarray005 @ArkadiK94 sorry for the late response
 
> You don't need to clear input if we have show password so the user could change typo and so on.

this one is also a good option

> about clearing password
 
 if user keep entering wrong password, it will lock their account for 30mins
 example user is using caps lock without knowingly.

**Comment by kabir0x23** [comment]
i thhink this is better option

 >   You don't need to clear input if we have show password so the user could change typo and so on.

**Comment by ArkadiK94** [comment]
@AhmedKarray005 I changed the title, to add show password button, would you like to handle it? 
Don't remove the incorrect text on wrong submission.

**Comment by AhmedKarray005** [comment]
@ArkadiK94 yes i would like to

**Comment by AhmedKarray005** [comment]
@ArkadiK94 

https://github.com/thecyberworld/TheCyberHUB/assets/104280658/d5344314-895f-469b-9328-76503f0606d3

**Comment by AhmedKarray005** [comment]
@ArkadiK94

**Comment by ArkadiK94** [comment]
@AhmedKarray005 I think it is better to add some margin bottom to emphasize that this related to the password input box. Beside it, looks great thanks. Could you open a pr?

**Comment by kabir0x23** [comment]
https://react-icons.github.io/react-icons/ u can get icons from here

import { BiHide,BiShowAlt } from "react-icons/bi";

<BiHide />


<BiShowAlt />

**Comment by AhmedKarray005** [comment]
@kabir0x23 @ArkadiK94 

https://github.com/thecyberworld/TheCyberHUB/assets/104280658/6bbc4dc5-8986-4491-82db-e47509cf470b

**Comment by AhmedKarray005** [comment]
@ArkadiK94 i create a pr?

**Comment by ArkadiK94** [comment]
@AhmedKarray005 yes, even though, I am not sure of the icons. I think when you see the password the eye should be without cross and the opposite.

**Comment by ArkadiK94** [comment]
@kabir0x23 I need to look for similar examples. Do you know which way is correct? Of the icons?

**Comment by kabir0x23** [comment]
i think it's fine,

example
<img width="268" alt="Screenshot 2024-05-19 at 11 50 01 PM" src="https://github.com/thecyberworld/TheCyberHUB/assets/44284877/8a69e77b-56ba-49c4-83f1-89d2be2aa1bf">

**Comment by ArkadiK94** [comment]
I found example :) 
I don't know haha very hard question, who is right

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/7ce31203-698e-48a2-be4b-8a86c281b095

**Comment by kabir0x23** [comment]
yes in facebook, it is showing what is there

in my example and his pr, it is about what to do 

on buttons we do that task



here 
<img width="280" alt="image" src="https://github.com/thecyberworld/TheCyberHUB/assets/44284877/0787b6bc-124b-4320-87ee-76dabae41724">

arrow is above, when we click, it will bring the tab and icon will be down after words


without getting confused, it's fine  for now, will it decide later

**Comment by kabir0x23** [comment]
<img width="539" alt="Screenshot 2024-05-20 at 12 14 40 AM" src="https://github.com/thecyberworld/TheCyberHUB/assets/44284877/da10b374-f299-4c40-b493-4b36f0fa7c18">

example of linkedin, 

show means open eye
hide means crossed eye

**Comment by ArkadiK94** [comment]
@kabir0x23 ok great, @AhmedKarray005 yes please open the pr

**Comment by ArkadiK94** [comment]
@AhmedKarray005 is it ok the someone else will work on it? I saw that someone opened new pr

![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/5f39d6f7-eee0-4ebb-b927-3b2ce7fa7048)
