### ISSUE TITLE
[BUG] Sidebar overflowing in explore

### ISSUE THREAD

**Issue by seifnamissi** [thecyberworld/TheCyberHUB#781]
### Describe the bug

Problem with UI 

### To Reproduce

go to explore 
see left sidebar

### Screenshot/ Video

![image](https://github.com/thecyberworld/TheCyberHUB/assets/152433554/5e30eb97-4bd3-427c-a7a1-791094b6d38c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@seifnamissi maybe fixed, in a pr which pending for code review so let's wait it to be merged and we will see. For now, I am not closing this issue.

**Comment by ArkadiK94** [comment]
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/0db64864-f651-4377-961c-e574475603d3)

It was fixed as I see now, @seifnamissi after you will sync, if you still see this bug please open this issue again. I will close this right now.
