### ISSUE TITLE
[BUG] Edit Profile navigating to 404 not found page

### ISSUE THREAD

**Issue by Jazzxe** [thecyberworld/TheCyberHUB#787]
### Describe the bug

When trying to edit profile, the button does not function on first listener, Onclicking several times it keeps you in the same page most of the times, generates 404 not found page more frequently.

### To Reproduce

1- go to Public profile
2- Click on Edit profile
3- Two possible outcomes : 
                                    3.1 static behaviour ( no navigation);
                                    3.2 404 not found page

### Expected Behavior

Navigation to a profile editing Interface;

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@Jazzxe Thanks for finding such a bug, would you like to work on it?

Note: next time please add screenshot or short video.

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/928ab6d9-b095-49dd-96f5-d8c360a7db82
