### ISSUE TITLE
[FEATURE] Analytics | Add Functionality For Download Button

### ISSUE THREAD

**Issue by Tamir198** [thecyberworld/TheCyberHUB#800]
### Detailed description

Right now this button is not doing anything : 

[FEATURE] Analytics | Add Functionality For Analytics Page

### Context

I was thinking it could save the different graph data from this page for example.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/c307b2f2-f343-471c-b840-5d6c5a94879d)

**Comment by ArkadiK94** [comment]
@kabir0x23 do we have in backend option to download pdf files?

**Comment by kabir0x23** [comment]
> @kabir0x23 do we have in backend option to download data as pdf files?

we dont have anything in backend for now, we can skip this or add sampledata.cve file or json

with data we have mentnioend

actually that dowload button will download our analytics data, we can create. a function to create a json or cve file data with dummy data we have

**Comment by kabir0x23** [comment]
we dont have to have a file to download, 

click on download button (data -> file(cve/json))

**Comment by Tamir198** [comment]
> > @kabir0x23 do we have in backend option to download data as pdf files?
> 
> we dont have anything in backend for now, we can skip this or add sampledata.cve file or json
> 
> with data we have mentnioend
> 
> actually that dowload button will download our analytics data, we can create. a function to create a json or cve file data with dummy data we have

Sounds good I will create a function that creates CVS file with the data and download it.

**Comment by Tamir198** [comment]
@kabir0x23  Hey are you ok with me adding [react-csv](https://www.npmjs.com/package/react-csv) library for the file creation?

**Comment by kabir0x23** [comment]
yes we can, it is safe library we can go with it
