### ISSUE TITLE
[Bug] Glitch in Navigation Bar in Brave Browser

### ISSUE THREAD

**Issue by infotechprogrammer** [thecyberworld/TheCyberHUB#801]
### Detailed description

The website is not working appropriately:
- The navigation bar in header where we hover and items come
- Those items are visible all over the website on scrolling

![image](https://github.com/thecyberworld/TheCyberHUB/assets/78542194/3b3f24ef-5371-4cae-b399-9f1dd62246e5)

### To Reproduce

-

### Expected Behavior

It should not come all over the screen at scrolling

### Screenshot/ Video of the Responsive Problem

![image](https://github.com/thecyberworld/TheCyberHUB/assets/78542194/08047188-c4ae-40ac-accc-d18d70ae2847)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@kabir0x23 we talked about it, that we should add more blur in bg.

**Comment by kabir0x23** [comment]
> @kabir0x23 we talked about it, that we should add more blur in bg.

in 1-2 browser this is a the actual issues

WITH blur it is looking like this

<img width="1440" alt="Screenshot 2024-05-18 at 6 34 27 PM" src="https://github.com/thecyberworld/TheCyberHUB/assets/44284877/1f479551-893f-437f-96ec-95801646a398">


but above screenshot is just transparent

**Comment by kabir0x23** [comment]
<img width="1440" alt="image" src="https://github.com/thecyberworld/TheCyberHUB/assets/44284877/5f7b76e6-5238-492d-a71d-bed908cb9933">

**Comment by ArkadiK94** [comment]
@kabir0x23 yup, so let's return the bg color as was before maybe
