### ISSUE TITLE
[Responsive-Web] Search/Sidebar width not full in small screen

### ISSUE THREAD

**Issue by infotechprogrammer** [thecyberworld/TheCyberHUB#802]
### Detailed description

See the search bar and all you see in header should be in full width, but is coming in center with less width and looks dull and creepy.

![image](https://github.com/thecyberworld/TheCyberHUB/assets/78542194/253b43d0-ed4b-4ad2-9e38-34c5f90af411)

### To Reproduce

-

### Expected Behavior

Width must be full according to screen

### Screenshot/ Video of the Responsive Problem

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alvarotorrestx** [comment]
Hi i'd like to work on this, I just put a PR for a similar issue on the Feeds page, I'd like to use similar style to this, please assign if acceptable 😊

**Comment by ArkadiK94** [comment]
@alvarotorrestx ok, I assigned you, however, if you are going to use the same style as in feeds please first wait for review about the feeds pr.

**Comment by alvarotorrestx** [comment]
@ArkadiK94 ok sure got it 👌

**Comment by ArkadiK94** [comment]
@alvarotorrestx hi, would you like to work on it? or is it ok that @sahil28032005 will do it?

**Comment by alvarotorrestx** [comment]
> @alvarotorrestx hi, would you like to work on it? or is it ok that @sahil28032005 will do it?

He can work on it, that is fine, I am working on the other referenced issue
