### ISSUE TITLE
[Responsive-Web] Chat sidebar auto-hiding is not in working in small screen

### ISSUE THREAD

**Issue by infotechprogrammer** [thecyberworld/TheCyberHUB#804]
### Detailed description

Bad behavior of screen, not auto hiding elements:

Chat sidebar auto-hiding is not in working in small screen at first place.

![image](https://github.com/thecyberworld/TheCyberHUB/assets/78542194/dcf655de-e35e-4c4b-b61b-033ea87ec68a)

### To Reproduce

-

### Expected Behavior

-

### Screenshot/ Video of the Responsive Problem

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gitkrishnapathak** [comment]
@ArkadiK94 HI, please assign me.
