### ISSUE TITLE
[Responsive-Web] AI new chat section is not responsive

### ISSUE THREAD

**Issue by infotechprogrammer** [thecyberworld/TheCyberHUB#805]
### Detailed description

AI new chat section is not responsive.

On big screen design is not appropriate

![image](https://github.com/thecyberworld/TheCyberHUB/assets/78542194/1439fcff-2e82-43a7-87b9-8477c888879a)

### To Reproduce

-

### Expected Behavior

-

### Screenshot/ Video of the Responsive Problem

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sky-De** [comment]
@ArkadiK94 hi there, please assign this to me, thanks

**Comment by Sky-De** [comment]
@ArkadiK94 @infotechprogrammer i can not find the same page with that UI that you have mentioned, in local code, there is AI section but UI is different than you attached, also there is no AI section in live running project,

![chrome-capture-2024-4-21](https://github.com/thecyberworld/TheCyberHUB/assets/79264045/a24b78d1-79e5-458b-8556-cd2214dc0f17)

**Comment by ArkadiK94** [comment]
@Sky-De 
https://dev.thecyberhub.org/#/aiChat

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/795ff3af-bcb6-4a6a-9b00-e199707216f9

**Comment by Sky-De** [comment]
@ArkadiK94 I can not log in for an unknown reason, can you help me with it, please? I have tried both local and live site

https://github.com/thecyberworld/TheCyberHUB/assets/79264045/859dc947-98df-466a-8baa-30ad8f2bf616

**Comment by ArkadiK94** [comment]
@Sky-De you need to login with username, not email address

**Comment by Sky-De** [comment]
@ArkadiK94 how can i know what is my user name?

**Comment by ArkadiK94** [comment]
@Sky-De Great question, the username that you wrote when you registered

**Comment by kabir0x23** [comment]
https://dev.thecyberhub.org/#/leaderboard from here we can check usernames

**Comment by ArkadiK94** [comment]
> > @Sky-De Great question, the username that you wrote when you registered
> 
> @ArkadiK94 Greate ANSWER, so what about the person who wants to just join and check out what is going on, on this platform and just quickly fill in the blanks? ( users most of the time do not care about trivial things such as username, the same thing that happened to me ), then without that userName, he/she will not be able to log in again, align with best practices there should be a possibility to log in with an email address and userName/number which email address always has priority over others, now after whole these what happens for a user who forgets his/her user name?
> 
> Also @kabir0x23 this link [https://dev.thecyberhub.org/#/leaderboard ](https://dev.thecyberhub.org/#/leaderboard) was not helpful, Unfortunately.
> 
> Please think about creating an issue to fix all auth flaws, thanks,sky-de

@Sky-De  Thank you for your feedback, we will discuss the option to change to login with email address instead.

**Comment by kabir0x23** [comment]
HI

we are sharing usernames in forgot password in next update,

and we dont have any email in our data base the u have mentiioned in video sky....

can u can check your different email and can search for thecyberhub emails to check which email u have used

from next update, we are only accepting emails instead of usernames for security improvements


thanks

**Comment by ArkadiK94** [comment]
@Sky-De Hi, we looked in the dev environment db and your email is not there but it is in main environment db.
You need to register again in the dev environment 
dev.thecyberhub.org

**Comment by ArkadiK94** [comment]
@Sky-De Hi, how is it going?

**Comment by ArkadiK94** [comment]
@Sky-De I an assigned you tell us if you would like to work on it so I will re assign you

**Comment by SinanovicAhmed** [comment]
@ArkadiK94 I don't know if this is what you imagined it to be. I also changed how recent chats
 component behaves under 800px screen size so it doesn't get to overcrowded on mobile devices.

[screen-capture (1).webm](https://github.com/thecyberworld/TheCyberHUB/assets/93159428/f0a5ffc1-c768-4006-92f3-8c2848df0e60)

**Comment by ArkadiK94** [comment]
@SinanovicAhmed Thanks for your contribution please one pr so we will review it.
By the way, next time, please ask to be assigned so we will know that you are working on it.

**Comment by SinanovicAhmed** [comment]
> @SinanovicAhmed Thanks for your contribution please one pr so we will review it. By the way, next time, please ask to be assigned so we will know that you are working on it.

I just took a peek while drinking coffee and got carried away :)

**Comment by ArkadiK94** [comment]
@SinanovicAhmed Know this feeling, when there is a challenge to solve I need a reminder to drink, eat, and sleep 😜
