### ISSUE TITLE
[BUG] Font Color error in Goals section on dashboard

### ISSUE THREAD

**Issue by Shubham-2k1** [thecyberworld/TheCyberHUB#813]
### Describe the bug

Whatever we add in Goals section the font color is white on white background making it hard to visible 
![goals](https://github.com/thecyberworld/TheCyberHUB/assets/71768868/0da92c69-d335-43c7-b63d-c8d0a5879d04)

### To Reproduce

Go to Dashboard 
Go to Goals 
Enter anything

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alvarotorrestx** [comment]
Hey, I'd like to help, can you assign me please?
