### ISSUE TITLE
[FEATURE] Dashboard | Add copy button to encoded fields

### ISSUE THREAD

**Issue by Tamir198** [thecyberworld/TheCyberHUB#818]
### Detailed description

Go to the dashboard/encoder  : 

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/38546e95-8d65-48a9-9713-0bbac29c2a29)
![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/6137b50b-79c9-4ee9-97d5-2d959de7f177)
![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/6f031dd1-c229-4926-8c6e-7edb08719563)

### Context

I think that we should add copy button next to every line so we can copy the encoded data easily 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@Tamir198 In my opinion, very useful idea.
@kabir0x23 what do you think?

**Comment by ArkadiK94** [comment]
@Tamir198 You can start working on it. Thanks for raising this issue.
