### ISSUE TITLE
[BUG] encoder | hover color covers the text

### ISSUE THREAD

**Issue by Tamir198** [thecyberworld/TheCyberHUB#820]
### Describe the bug

Inside the encoder (dashboard -> tools -> encoder) there is a text field with the same background color and text color on hover. 

### To Reproduce

Go to the dashboard -> tools -> encoder : 

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/49f708c3-e38c-4172-ad1c-454d6feecca4)
![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/f2541b68-7013-4c96-b346-c9fae2c7846b)

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/645d3d11-4803-41c1-87ff-4054a769139c)

When you hover the text field the color (white) is the same as the background (also white on hover) and this makes the text "vanish" :

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/f459814b-4f73-4959-8ed4-5b0697f85ffb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tamir198** [comment]
I could fix this, should we change the background color on hover or the text color on hover?

**Comment by ArkadiK94** [comment]
@Tamir198 Make sure that you understand that the problem is in display.css file that someone created... I gives a lot of styles overwrites and make problem all over the app O_O
