### ISSUE TITLE
[BUG] Facebook community social link briken 

### ISSUE THREAD

**Issue by Tamir198** [thecyberworld/TheCyberHUB#828]
### Describe the bug

Facebook link in here is broken (content not available)

![image](https://github.com/thecyberworld/TheCyberHUB/assets/34707669/f69ac4c7-fcc6-4b7c-94c5-ab5fce5cb564)

### To Reproduce

To do https://dev.thecyberhub.org/#/community and you will have a Facebook button

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ArkadiK94** [comment]
@kabir0x23 do we have Facebook page for the community? If so, what is the link?

**Comment by kabir0x23** [comment]
> @kabir0x23 do we have Facebook page for the community? If so, what is the link?

yes, in comunnity we have old one

new: https://www.facebook.com/thecyberworldcommunity/

**Comment by ArkadiK94** [comment]
@Tamir198 would you like to fix it?

**Comment by Tamir198** [comment]
@ArkadiK94  sure
