### ISSUE TITLE
[Responsive-Web] AI Chat | change position of opened left menu

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#865]
### Detailed description

when left menu opens it slides inside the "New Chat" In my opinion, it should be instead.

### To Reproduce

Go to AI page
Change to width for mobile/tablet example width 800
Click on orange button to toggle left menu

### Expected Behavior

The left menu should be instead of right section - the chat 

### Screenshot/ Video of the Responsive Problem

Current:
![339868729-366a415a-455d-4bd3-9c42-f4e993e42d22](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/9294b649-c08a-40fe-8298-65b01d17a6e8)

Need to change it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GFerreiroS** [comment]
Hi, can i look into it? What do you mean it needs to be right?

**Comment by GFerreiroS** [comment]
Okay i did understand now, its resolved. Will create a pull request.

**Comment by ArkadiK94** [comment]
@GFerreiroS nope, I will explain. When you click the arrow the left menu slides inside the right menu. You can see it because you still see the header "New Chat". 

Change it to be:
When clicking the arrow the left menu will replace the right(side) menu.

**Comment by GFerreiroS** [comment]
Thanks for the explanation, now should be fixed, just one question do you want to have the same button style?


https://github.com/thecyberworld/TheCyberHUB/assets/131366333/9e3464d6-f792-43f3-a5a0-fdd08156c02d

**Comment by ArkadiK94** [comment]
@GFerreiroS I think yes, the same button style.
