### ISSUE TITLE
[BUG] AIChat | remove the black lines

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#867]
### Describe the bug

AIChat | remove the black lines, they appear when I click around, I use Firefox browser

### To Reproduce

Go to AI page
Change the screen width to 1339
Click around the screen
See black lines

### Expected Behavior

Remove those lines

### Screenshot/ Video

https://github.com/thecyberworld/TheCyberHUB/assets/76536506/965e67de-a874-4959-a2b5-5db10c381ec5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
i think this is comming from browser, i am also getting differnt one, no issue with code

![image](https://github.com/thecyberworld/TheCyberHUB/assets/44284877/7f90e745-556d-45ae-8cf6-a7ef86ec359a)

**Comment by GFerreiroS** [comment]
Hi i am trying to replicate it, but i see it all ok, tested with safari, chrome, firefox and arc.

**Comment by ArkadiK94** [comment]
@GFerreiroS try to change the screen width.

**Comment by GFerreiroS** [comment]
Here is moving the windows. I have tried in windows too and it isnt there the black line

https://github.com/thecyberworld/TheCyberHUB/assets/131366333/b3a783dd-3613-415d-ab05-5257a3dbfbfc

**Comment by ArkadiK94** [comment]
@GFerreiroS you need to click around with the mouse

**Comment by ArkadiK94** [comment]
@kabir0x23 so do you think that this issue is not legit?
