### ISSUE TITLE
[BUG] AI | hide 3 dots, fix input field mode for not logged in user

### ISSUE THREAD

**Issue by ArkadiK94** [thecyberworld/TheCyberHUB#869]
### Describe the bug

- [ ] hide the three dots icon, until we will add functionality
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/d7d72042-de78-4807-9ce1-d475076ee157)

- [ ] fix input field -  it doesn't respond when user is not logged in. When user clicks / focus on it open existing window of login

![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/8e45baeb-89b6-45aa-8191-fd098b1c9464)

The window that asks the user to login:
![image](https://github.com/thecyberworld/TheCyberHUB/assets/76536506/5bc87e53-9542-4903-bc5d-b4468b208514)

### To Reproduce

Go to AI page

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GFerreiroS** [comment]
Hi can i be assigned?

**Comment by SandipGyawali** [comment]
@ArkadiK94 can i look at it ?

**Comment by ArkadiK94** [comment]
@SandipGyawali Yeah sure, if you have any questions don't hesitate to ask :)

**Comment by dev-px** [comment]
Can I look at it ??

**Comment by ArkadiK94** [comment]
@dev-px someone is already assigned to it.

**Comment by ArkadiK94** [comment]
@dev-px you can try one of the other issues which no one is assigned to.

**Comment by ArkadiK94** [comment]
@dev-px https://github.com/thecyberworld/TheCyberHUB/issues/560
would you like to work on issue 560?
